### ISSUE TITLE
problem with init.weights()

### ISSUE THREAD

**Issue by marouaneamz** [open-mmlab/mmclassification#1005]
### Checklist

- I have searched related issues but cannot get the expected help.

### Describe the question you meet

i have a probleme http 404 when i use model.init_weights()

### Post related information

1. The output : 
```
Traceback (most recent call last):
  File "mobilenet.py", line 81, in <module>
    model.init_weights()
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/site-packages/mmcv/runner/base_module.py", line 117, in init_weights
    m.init_weights()
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/site-packages/mmcv/runner/base_module.py", line 106, in init_weights
    initialize(self, self.init_cfg)
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/site-packages/mmcv/cnn/utils/weight_init.py", line 636, in initialize
    _initialize(module, cp_cfg)
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/site-packages/mmcv/cnn/utils/weight_init.py", line 539, in _initialize
    func(module)
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/site-packages/mmcv/cnn/utils/weight_init.py", line 520, in __call__
    self.prefix, self.checkpoint, map_location=self.map_location)
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 582, in _load_checkpoint_with_pr
efix
    checkpoint = _load_checkpoint(filename, map_location=map_location)
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 561, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 303, in load_checkpoint
    return checkpoint_loader(filename, map_location)  # type: ignore
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 348, in load_from_http
    filename, model_dir=model_dir, map_location=map_location)
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/site-packages/torch/hub.py", line 555, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/site-packages/torch/hub.py", line 425, in download_url_to_file
    u = urlopen(req)
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/marouane/anaconda3/envs/pytorch17/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by Ezra-Yu** [comment]
Do you use the pre-trained checkpoints? Can you show your config?

**Comment by marouaneamz** [comment]
> 

```
# Specify the path of the config file and checkpoint file.
config_file = './mobilenet-v2_8xb32_in1k.py'
checkpoint_file = 'https://download.openmmlab.com/mmclassification/v0/mobilenet_v2/mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth'

# Load the base config file
from mmcv import Config
cfg = Config.fromfile('/home/marouane/dev/mdl-py-classification/model/mobile/mobilenet-v2_8xb32_in1k.py')

# Modify the number of classes in the head.
cfg.model.head.num_classes = 19
cfg.model.head.topk = (1, )

# Load the pre-trained model's checkpoint.
cfg.model.backbone.init_cfg = dict(type='Pretrained', checkpoint=checkpoint_file, prefix='backbone')

# Specify sample size and number of workers.
cfg.data.samples_per_gpu = 32
cfg.data.workers_per_gpu = 8

# Specify the path and meta files of training dataset
cfg.data.train.data_prefix = '/home/marouane/dev/mdl-py-classification/model/data_split/train'
cfg.data.train.classes = '/home/marouane/dev/mdl-py-classification/model/data_split/classes.txt'

# Specify the path and meta files of validation dataset
cfg.data.val.data_prefix = '/home/marouane/dev/mdl-py-classification/model/data_split/val'
cfg.data.val.ann_file = '/home/marouane/dev/mdl-py-classification/model/data_split/val.txt'
cfg.data.val.classes = '/home/marouane/dev/mdl-py-classification/model/data_split/classes.txt'

# Specify the path and meta files of test dataset
cfg.data.test.data_prefix = '/home/marouane/dev/mdl-py-classification/model/data_split/test'
cfg.data.test.ann_file = '/home/marouane/dev/mdl-py-classification/model/data_split/test.txt'
cfg.data.test.classes = '/home/marouane/dev/mdl-py-classification/model/data_split/classes.txt'



# Modify the evaluation metric
cfg.evaluation['metric_options']={'topk': (1, )}

# Specify the optimizer
cfg.optimizer = dict(type='SGD', lr=0.005, momentum=0.9, weight_decay=0.0001)
cfg.optimizer_config = dict(grad_clip=None)

# Specify the learning rate scheduler
cfg.lr_config = dict(policy='step', step=1, gamma=0.1)
cfg.runner = dict(type='EpochBasedRunner', max_epochs=10)

# Specify the work directory
cfg.work_dir = './work_dirs/horse_dataset'
# Output logs for every 10 iterations
cfg.log_config.interval = 50
cfg.device = 'cuda'

# Set the random seed and enable the deterministic option of cuDNN
# to keep the results' reproducible.
from mmcls.apis import set_random_seed
cfg.seed = 0
set_random_seed(0, deterministic=True)

cfg.gpu_ids = range(1)

# Create the work directory
mmcv.mkdir_or_exist(osp.abspath(cfg.work_dir))
# Build the classifier
model = build_classifier(cfg.model)
model.init_weights()
# Build the dataset
```

**Comment by Ezra-Yu** [comment]
It seems a network error, you can download the pre-trained checkpoint manually,
run  ```wget https://download.openmmlab.com/mmclassification/v0/mobilenet_v2/mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth```
or copy the link and paste into your browser like Chrome.

then change `checkpoint_file` value
```
checkpoint_file = "LOACL_CHECKPOINT_PATH"
```

**Comment by marouaneamz** [comment]
> It seems a network error, you can download the pre-trained checkpoint manually, run `wget https://download.openmmlab.com/mmclassification/v0/mobilenet_v2/mobilenet_v2_batch256_imagenet_20200708-3b2dc3af.pth` or copy the link and paste into your browser like Chrome.
> 
> then change `checkpoint_file` value
> 
> ```
> checkpoint_file = "LOACL_CHECKPOINT_PATH"
> ```

it's okey for me
