### ISSUE TITLE
Customize dataset :KeyError: Caught KeyError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by Sean-hku** [open-mmlab/mmclassification#101]
**Hi, I run `train.py` using my customize dataset according to `Tutorial 2: Adding New Dataset`, and I get an error:**

2020-11-26 16:41:35,990 - mmcls - INFO - Start running, host: hkuit164@hkuit164-desktop, work_dir: /media/hkuit164/TOSHIBA/mmclassification/tools/work_dirs/restnet18
2020-11-26 16:41:35,990 - mmcls - INFO - workflow: [('train', 1)], max: 200 epochs
Traceback (most recent call last):
  File "/media/hkuit164/TOSHIBA/mmclassification/tools/train.py", line 157, in <module>
    main()
  File "/media/hkuit164/TOSHIBA/mmclassification/tools/train.py", line 153, in main
    meta=meta)
  File "/media/hkuit164/TOSHIBA/mmclassification/mmcls/apis/train.py", line 133, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/home/hkuit164/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/hkuit164/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/hkuit164/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/hkuit164/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/hkuit164/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/hkuit164/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/hkuit164/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/hkuit164/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hkuit164/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/hkuit164/TOSHIBA/mmclassification/mmcls/datasets/base_dataset.py", line 86, in __getitem__
    return self.prepare_data(idx)
  File "/media/hkuit164/TOSHIBA/mmclassification/mmcls/datasets/base_dataset.py", line 80, in prepare_data
    return self.pipeline(results)
  File "/media/hkuit164/TOSHIBA/mmclassification/mmcls/datasets/pipelines/compose.py", line 32, in __call__
    data = t(data)
  File "/media/hkuit164/TOSHIBA/mmclassification/mmcls/datasets/pipelines/transforms.py", line 98, in __call__
    img = results[key]
KeyError: 'img'

Process finished with exit code 1

**I just add a `filelist.py` in `mmcls/datasets/filelist.py` and modify the dataset_type to the same name of filelist. Here is my filelist.py.**

`import mmcv
import numpy as np

from .builder import DATASETS
from .base_dataset import BaseDataset

@DATASETS.register_module()
class MyDataset(BaseDataset):

    def load_annotations(self):
        assert isinstance(self.ann_file, str)

        data_infos = []
        with open(self.ann_file) as f:
            samples = [x.strip().split(' ') for x in f.readlines()]
            for filename, gt_label in samples:
                # print(filename)
                info = {'img_prefix': self.data_prefix}
                info['img_info'] = {'filename': filename}
                info['gt_label'] = np.array(gt_label, dtype=np.int64)
                data_infos.append(info)
            return data_infos`

**Comment by KasperSHenriksen** [comment]
Hi Sean-hku and others who encounters this issue. I think this is an issue with using configs that are based on cifar10. I was able to prevent this issue by changing the resnet config from _resnet18_b16x8_cifar10.py_ to _resnet18_b32x8_imagenet.py_.

**Comment by mzr1996** [comment]
Hello, this problem is because of the missing `LoadImageFromFile` in the pipeline.
Because the CIFAR dataset is packaged in a `pkl` file, so `resnet18_b16x8_cifar10.py` won't use `LoadImageFromFile` in its pipeline.
Please add it in the train and test pipeline, which refers to `resnet18_b32x8_imagenet.py`.
