### ISSUE TITLE
KeyError: 'LinearHead is not in the head registry'

### ISSUE THREAD

**Issue by fengyouliang** [open-mmlab/mmclassification#105]
use config
```python
model = dict(
    head=dict(
        type='LinearHead',
        num_classes=1000,
        in_channels=2048,
        loss=dict(
            type='LabelSmoothLoss',
            loss_weight=1.0,
            label_smooth_val=0.1,
            num_classes=1000),
    ))
```

got trackback
```python
Traceback (most recent call last):
  File "/home/code/open_mmlab_codebase/huatian_bump_blur_cls/tools/train.py", line 177, in <module>
    main()
  File "/home/code/open_mmlab_codebase/huatian_bump_blur_cls/tools/train.py", line 151, in main
    model = build_classifier(cfg.model)
  File "/home/code/open_mmlab_codebase/mmclassification/mmcls/models/builder.py", line 38, in build_classifier
    return build(cfg, CLASSIFIERS)
  File "/home/code/open_mmlab_codebase/mmclassification/mmcls/models/builder.py", line 18, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/home/code/open_mmlab_codebase/mmclassification/mmcls/models/classifiers/image.py", line 18, in __init__
    self.head = build_head(head)
  File "/home/code/open_mmlab_codebase/mmclassification/mmcls/models/builder.py", line 26, in build_head
    return build(cfg, HEADS)
  File "/home/code/open_mmlab_codebase/mmclassification/mmcls/models/builder.py", line 18, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 164, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'LinearHead is not in the head registry'
```

__check /mmcls/models/heads/*.py, not exist `LinearHead` registered__

**Comment by fengyouliang** [comment]
it is a typo? i change type from `LinearHead` to `LinearClsHead`, it works!

**Comment by wangruohui** [comment]
It seems to be. Feel free to submit a pull request for this bug.
