### ISSUE TITLE
[Bug] 'ConfigDict' object has no attribute 'log_level'

### ISSUE THREAD

**Issue by Laymanpython** [open-mmlab/mmclassification#1104]
### 描述该错误

When I used my dataset to train resnet ,the terminal told me that 'ConfigDict' object has no attribute 'log_level'.I can't find it's solution  on the  other  website.

### 环境信息

Traceback (most recent call last):
  File "tools/train.py", line 206, in <module>
    main()
  File "tools/train.py", line 149, in main
    logger = get_root_logger(log_file=log_file, log_level=cfg.log_level)
  File "/home/lixin/mmclassification/lib/python3.8/site-packages/mmcv/utils/config.py", line 519, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/lixin/mmclassification/lib/python3.8/site-packages/mmcv/utils/config.py", line 50, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'log_level'

**Comment by mzr1996** [comment]
Can you provide your config file?
