### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ljwLJW12** [open-mmlab/mmclassification#1205]
### 分支

master 分支 (0.24 或其他 0.x 版本)

### 描述该错误

2022-11-17 15:27:37,639 - mmcls - INFO - Set random seed to 1885459642, deterministic: False
C:\Users\59192\.conda\envs\mmcla\lib\site-packages\mmcv\cnn\bricks\conv_module.py:154: UserWarning: Unnecessary conv bias before batch/instance norm
  'Unnecessary conv bias before batch/instance norm')
2022-11-17 15:27:38,202 - mmcls - INFO - initialize VGG with init_cfg [{'type': 'Kaiming', 'layer': ['Conv2d']}, {'type': 'Constant', 'val': 1.0, 'layer': ['_BatchNorm']}, {'type': 'Normal', 'std': 0.01, 'layer': ['Linear']}]
Traceback (most recent call last):
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\mmcv\utils\registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "C:\Users\59192\mmclassification\mmcls\datasets\imagenet.py", line 1060, in __init__
    file_client_args=file_client_args)
  File "C:\Users\59192\mmclassification\mmcls\datasets\custom.py", line 170, in __init__
    test_mode=test_mode)
  File "C:\Users\59192\mmclassification\mmcls\datasets\base_dataset.py", line 51, in __init__
    self.data_infos = self.load_annotations()
  File "C:\Users\59192\mmclassification\mmcls\datasets\custom.py", line 211, in load_annotations
    samples = self._find_samples()
  File "C:\Users\59192\mmclassification\mmcls\datasets\custom.py", line 175, in _find_samples
    self.data_prefix)
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\mmcv\fileio\file_client.py", line 896, in infer_client
    return cls(prefix=file_prefix)
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\mmcv\fileio\file_client.py", line 814, in __new__
    f'prefix {prefix} is not supported. Currently supported ones '
ValueError: prefix C is not supported. Currently supported ones are ['s3', 'http', 'https']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\59192\mmclassification\tools\train.py", line 205, in <module>
    main()
  File "C:\Users\59192\mmclassification\tools\train.py", line 178, in main
    datasets = [build_dataset(cfg.data.train)]
  File "C:\Users\59192\mmclassification\mmcls\datasets\builder.py", line 55, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ValueError: ImageNet: prefix C is not supported. Currently supported ones are ['s3', 'http', 'https']

### 环境信息

(mmcla) C:\Users\59192\mmclassification> python -c "import mmcls.utils;import pprint;pprint.pp(dict(mmcls.utils.collect_env()))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'pprint' has no attribute 'pp'

**Comment by yingfhu** [comment]
`pprint.pp` is a new usage after python3.8, please check your python version, and use `pprint.pprint` instead

**Comment by mzr1996** [comment]
Please use path like `C:/data` instead of `C://data`

**Comment by ljwLJW12** [comment]
> Please use path like `C:/data` or `C:\\data` instead of `C://data`
If I use 'C:/data' or 'C: data', the following error will be reported
yapf.yapflib.verifier.InternalError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<string>, line 7)
Using 'C://data' will not cause the above problems, but will report errors
ValueError: ImageNet: prefix C is not supported. Currently supported ones are ['s3', 'http', 'https']

**Comment by mzr1996** [comment]
Sorry but I can not reproduce the error about `yapf`, please provide the entire error traceback.

**Comment by ljwLJW12** [comment]
> Sorry but I can not reproduce the error about `yapf`, please provide the entire error traceback.
Traceback (most recent call last):
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\yapf\yapflib\verifier.py", line 43, in VerifyCode
    compile(textwrap.dedent(code).encode('UTF-8'), '<string>', 'exec')
  File "<string>", line 8
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\yapf\yapflib\verifier.py", line 46, in VerifyCode
    ast.parse(textwrap.dedent(code.lstrip('\n')).lstrip(), '<string>', 'exec')
  File "C:\Users\59192\.conda\envs\mmcla\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<string>", line 7
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\yapf\yapflib\verifier.py", line 50, in VerifyCode
    compile(normalized_code.encode('UTF-8'), '<string>', 'exec')
  File "<string>", line 7
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\59192\mmclassification\tools\train.py", line 205, in <module>
    main()
  File "C:\Users\59192\mmclassification\tools\train.py", line 144, in main
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\mmcv\utils\config.py", line 596, in dump
    f.write(self.pretty_text)
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\mmcv\utils\config.py", line 508, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\yapf\yapflib\yapf_api.py", line 167, in FormatCode
    _SplitSemicolons(uwlines), verify, lines)
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\yapf\yapflib\reformatter.py", line 107, in Reformat
    return _FormatFinalLines(final_lines, verify)
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\yapf\yapflib\reformatter.py", line 419, in _FormatFinalLines
    verifier.VerifyCode(formatted_code[-1])
  File "C:\Users\59192\.conda\envs\mmcla\lib\site-packages\yapf\yapflib\verifier.py", line 52, in VerifyCode
    raise InternalError(sys.exc_info()[1])
yapf.yapflib.verifier.InternalError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<string>, line 7)

**Comment by mzr1996** [comment]
Well, I think it should be an MMCV or yapf issue, and I will transfer this issue to MMCV.
