### ISSUE TITLE
[Bug] ImageToImageRetriever multi gpus bug

### ISSUE THREAD

**Issue by okotaku** [open-mmlab/mmclassification#1310]
### Branch

1.x branch (1.0.0rc2 or other 1.x version)

### Describe the bug

https://github.com/open-mmlab/mmclassification/blob/dev-1.x/mmcls/models/retrievers/image2image.py#L265

Except for the main process, this part of the assert does not go through.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mmcls/.mim/tools/train.py", line 162, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/mmcls/.mim/tools/train.py", line 158, in main
    runner.train()
  File "/usr/local/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1678, in train
    model = self.train_loop.run()  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/mmengine/runner/loops.py", line 96, in run
    self.runner.val_loop.run()
  File "/usr/local/lib/python3.8/site-packages/mmengine/runner/loops.py", line 347, in run
    self.run_iter(idx, data_batch)
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mmengine/runner/loops.py", line 367, in run_iter
    outputs = self.runner.model.val_step(data_batch)
  File "/usr/local/lib/python3.8/site-packages/mmengine/model/wrappers/distributed.py", line 137, in val_step
    return self.module.val_step(data)
  File "/usr/local/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 133, in val_step
    return self._run_forward(data, mode='predict')  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 314, in _run_forward
    results = self(**data, mode=mode)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mmcls/models/retrievers/image2image.py", line 153, in forward
    return self.predict(inputs, data_samples)
  File "/usr/local/lib/python3.8/site-packages/mmcls/models/retrievers/image2image.py", line 217, in predict
    self.prepare_prototype()
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rpipecls/models/tmp.py", line 58, in prepare_prototype
    prototype_vecs = self._get_prototype_vecs_from_dataloader()
  File "/usr/local/lib/python3.8/site-packages/rpipecls/models/tmp.py", line 33, in _get_prototype_vecs_from_dataloader
    assert prototype_vecs is not None
AssertionError
`````

### Environment

multi gpus

```
mim train mmcls retriever_config.py --gpus 2 --launcher pytorch
```

### Other information

config

```
pretrained = 'https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_3rdparty-mill_in21k_20220331-faac000b.pth'
model = dict(
    type='ImageToImageRetriever',
    image_encoder=[
        dict(
            type='ResNet',
            depth=50,
            num_stages=4,
            out_indices=(3, ),
            style='pytorch',
            init_cfg=dict(
                type='Pretrained',
                checkpoint=
                'https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_3rdparty-mill_in21k_20220331-faac000b.pth',
                prefix='backbone')),
        dict(type='GlobalAveragePooling')
    ],
    head=dict(
        type='ArcFaceClsHead',
        num_classes=7982,
        in_channels=2048,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        init_cfg=None),
    prototype=dict(
        batch_size=8,
        num_workers=2,
        dataset=dict(
            type='InShop',
            data_root='data/inshop',
            split='gallery',
            test_mode=True,
            pipeline=[
                dict(type='LoadImageFromFile'),
                dict(type='Resize', scale=600),
                dict(type='CenterCrop', crop_size=448),
                dict(type='PackClsInputs')
            ]),
        sampler=dict(type='DefaultSampler', shuffle=False)))
dataset_type = 'InShop'
data_preprocessor = dict(
    num_classes=7982,
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', scale=600),
    dict(type='RandomCrop', crop_size=448),
    dict(type='RandomFlip', prob=0.5, direction='horizontal'),
    dict(type='PackClsInputs')
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', scale=600),
    dict(type='CenterCrop', crop_size=448),
    dict(type='PackClsInputs')
]
train_dataloader = dict(
    pin_memory=True,
    persistent_workers=True,
    collate_fn=dict(type='default_collate'),
    batch_size=32,
    num_workers=8,
    dataset=dict(
        type='InShop',
        data_root='data/inshop',
        split='train',
        test_mode=False,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', scale=600),
            dict(type='RandomCrop', crop_size=448),
            dict(type='RandomFlip', prob=0.5, direction='horizontal'),
            dict(type='PackClsInputs')
        ]),
    sampler=dict(type='DefaultSampler', shuffle=True))
query_dataloader = dict(
    batch_size=8,
    num_workers=2,
    dataset=dict(
        type='InShop',
        data_root='data/inshop',
        split='query',
        test_mode=True,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', scale=600),
            dict(type='CenterCrop', crop_size=448),
            dict(type='PackClsInputs')
        ]),
    sampler=dict(type='DefaultSampler', shuffle=False))
gallery_dataloader = dict(
    batch_size=8,
    num_workers=2,
    dataset=dict(
        type='InShop',
        data_root='data/inshop',
        split='gallery',
        test_mode=True,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', scale=600),
            dict(type='CenterCrop', crop_size=448),
            dict(type='PackClsInputs')
        ]),
    sampler=dict(type='DefaultSampler', shuffle=False))
val_dataloader = dict(
    pin_memory=True,
    persistent_workers=True,
    collate_fn=dict(type='default_collate'),
    batch_size=8,
    num_workers=2,
    dataset=dict(
        type='InShop',
        data_root='data/inshop',
        split='query',
        test_mode=True,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', scale=600),
            dict(type='CenterCrop', crop_size=448),
            dict(type='PackClsInputs')
        ]),
    sampler=dict(type='DefaultSampler', shuffle=False))
val_evaluator = dict(type='Accuracy', topk=(1, ))
test_dataloader = dict(
    pin_memory=True,
    persistent_workers=True,
    collate_fn=dict(type='default_collate'),
    batch_size=8,
    num_workers=2,
    dataset=dict(
        type='InShop',
        data_root='data/inshop',
        split='query',
        test_mode=True,
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', scale=600),
            dict(type='CenterCrop', crop_size=448),
            dict(type='PackClsInputs')
        ]),
    sampler=dict(type='DefaultSampler', shuffle=False))
test_evaluator = dict(type='Accuracy', topk=(1, ))
optim_wrapper = dict(
    optimizer=dict(
        type='AdamW',
        lr=0.0005,
        weight_decay=0.05,
        eps=1e-08,
        betas=(0.9, 0.999)))
param_scheduler = [
    dict(
        type='LinearLR',
        start_factor=0.01,
        by_epoch=True,
        begin=0,
        end=5,
        convert_to_iter_based=True,
        _scope_='mmcls'),
    dict(
        type='CosineAnnealingLR',
        T_max=95,
        by_epoch=True,
        begin=5,
        end=100,
        _scope_='mmcls')
]
train_cfg = dict(by_epoch=True, max_epochs=100, val_interval=1)
val_cfg = dict()
test_cfg = dict()
auto_scale_lr = dict(base_batch_size=64, enable=True)
default_scope = 'mmcls'
default_hooks = dict(
    timer=dict(type='IterTimerHook', _scope_='mmcls'),
    logger=dict(type='LoggerHook', interval=20, _scope_='mmcls'),
    param_scheduler=dict(type='ParamSchedulerHook', _scope_='mmcls'),
    checkpoint=dict(
        type='CheckpointHook',
        interval=1,
        _scope_='mmcls',
        save_best='auto',
        max_keep_ckpts=3),
    sampler_seed=dict(type='DistSamplerSeedHook', _scope_='mmcls'),
    visualization=dict(
        type='VisualizationHook', enable=False, _scope_='mmcls'))
env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'))
vis_backends = [dict(type='LocalVisBackend', _scope_='mmcls')]
visualizer = dict(
    type='ClsVisualizer',
    vis_backends=[dict(type='LocalVisBackend')],
    _scope_='mmcls')
log_level = 'INFO'
load_from = None
resume = False
randomness = dict(seed=None, deterministic=False)
custom_imports = dict(imports=['rpipecls'], allow_failed_imports=False)
custom_hooks = [dict(type='PrepareProtoBeforeValLoopHook', priority=48)]
launcher = 'pytorch'
work_dir = './work_dirs/resnet50-mil_2xb32_inshop'
```

**Comment by Ezra-Yu** [comment]
Here it may be triggered due to the progress bar, I will check it.
