### ISSUE TITLE
[Bug] 'ImageClassifier' object has no attribute 'module'

### ISSUE THREAD

**Issue by Shelwinliu** [open-mmlab/mmclassification#1344]
### Branch

master branch (0.24 or other 0.x version)

### Describe the bug

An error occurred while running tools/test.py.

I got the following error:
```python
D:\Env\Anaconda3\envs\openmmlab\python.exe E:/Projects/AI/mmclassification/tools/test.py ../configs/resnet/my_resnet18_8xb32_in1k.py ../tools/work_dirs/resnet18_8xb32_in1k/latest.pth --show-dir ../tools/work_dirs/resnet18_8xb32_in1k/val_result --metrics accuracy recall --device cpu
load checkpoint from local path: ../tools/work_dirs/resnet18_8xb32_in1k/latest.pth
[                                                  ] 0/818, elapsed: 0s, ETA:Traceback (most recent call last):
  File "E:/Projects/AI/mmclassification/tools/test.py", line 243, in <module>
    main()
  File "E:/Projects/AI/mmclassification/tools/test.py", line 194, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir,
  File "E:\Projects\AI\mmclassification\mmcls\apis\test.py", line 74, in single_gpu_test
    model.module.show_result(
  File "D:\Env\Anaconda3\envs\openmmlab\lib\site-packages\torch\nn\modules\module.py", line 1273, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ImageClassifier' object has no attribute 'module'
```

These are the configuration parameters I set before running:
```python
../configs/resnet/my_resnet18_8xb32_in1k.py
../tools/work_dirs/resnet18_8xb32_in1k/latest.pth
--show-dir
../tools/work_dirs/resnet18_8xb32_in1k/val_result
--metrics
accuracy
recall
--device
cpu
```

### Environment

```python
 {'sys.platform': 'win32',
 'Python': '3.8.16 (default, Jan 17 2023, 22:25:28) [MSC v.1916 64 bit '
           '(AMD64)]',
 'CUDA available': False,
 'MSVC': '用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.33.31630 版',
 'GCC': 'n/a',
 'PyTorch': '1.13.1',
 'PyTorch compiling details': 'PyTorch built with:\n'
                              '  - C++ Version: 199711\n'
                              '  - MSVC 192829337\n'
                              '  - Intel(R) Math Kernel Library Version '
                              '2020.0.2 Product Build 20200624 for Intel(R) 64 '
                              'architecture applications\n'
                              '  - Intel(R) MKL-DNN v2.6.0 (Git Hash '
                              '52b5f107dd9cf10910aaa19cb47f3abf9b349815)\n'
                              '  - OpenMP 2019\n'
                              '  - LAPACK is enabled (usually provided by '
                              'MKL)\n'
                              '  - CPU capability usage: AVX2\n'
                              '  - Build settings: BLAS_INFO=mkl, '
                              'BUILD_TYPE=Release, '
                              'CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, '
                              'CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w '
                              '/bigobj -DUSE_PTHREADPOOL -openmp:experimental '
                              '-IC:/cb/pytorch_1000000000000/work/mkl/include '
                              '-DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI '
                              '-DUSE_FBGEMM -DUSE_XNNPACK '
                              '-DSYMBOLICATE_MOBILE_DEBUG_HANDLE '
                              '-DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, '
                              'PERF_WITH_AVX=1, PERF_WITH_AVX2=1, '
                              'PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, '
                              'USE_CUDA=0, USE_CUDNN=OFF, USE_EXCEPTION_PTR=1, '
                              'USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, '
                              'USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, '
                              'USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, \n',
 'TorchVision': '0.14.1',
 'OpenCV': '4.7.0',
 'MMCV': '1.7.0',
 'MMCV Compiler': 'MSVC 192829924',
 'MMCV CUDA Compiler': 'not available',
 'MMClassification': '0.25.0+3d4f80d'}
```

### Other information

Obviously, the error points to mmcls/apis/test.py.

More specifically, the error is in these lines of code.
```python
model.module.show_result(
          img_show,
          result_show,
          show=show,
          out_file=out_file,
          **show_kwargs)
```

But when I modified it as following, the error disappeared.
```python
model.show_result(
          img_show,
          result_show,
          show=show,
          out_file=out_file,
          **show_kwargs)
```

**Comment by yingfhu** [comment]
The model used in single_gpu_test is assumed as `DistributedModel`, you can try following solutions alternatively:
1. Try use dist_test.sh script to start the test; or 
2. change the `model.module` to `model`

But I recommend use the 1.x branch, none of these modification is needed.
