### ISSUE TITLE
[Bug] Config format invalid after `tools/misc/print_config.py`

### ISSUE THREAD

**Issue by del-zhenwu** [open-mmlab/mmclassification#1361]
### Branch

master branch (0.24 or other 0.x version)

### Describe the bug

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 103, in _validate_py_syntax
    ast.parse(content)
  File "/opt/conda/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    Config:
          ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 243, in <module>
    main()
  File "tools/test.py", line 110, in main
    cfg = mmcv.Config.fromfile(args.config)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 341, in fromfile
    use_predefined_variables)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 207, in _file2dict
    Config._validate_py_syntax(filename)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/config.py", line 105, in _validate_py_syntax
    raise SyntaxError('There are syntax errors in config '
SyntaxError: There are syntax errors in config file /workspace/mmclassification/resnet34.py: invalid syntax (<unknown>, line 1)

```

### Environment

None

### Other information

```
python tools/misc/print_config.py configs/resnet/resnet34_8xb32_in1k.py > resnet34.py

```
"config: " showed in the first line in the `resnet34.py`

**Comment by Ezra-Yu** [comment]
This is a problem with the `tools/misc/print_config.py` in the master branch. The tool on the master branch is only for viewing the config. We are not currently going to update this tool in the master branch.

The `tools/misc/print_config.py` in the `1.x` branch does not have this problem.
