### ISSUE TITLE
[Bug] ImportError: cannot import name 'FileClient' from 'mmcv'

### ISSUE THREAD

**Issue by Xglbrilliant** [open-mmlab/mmclassification#1368]
### Branch

1.x branch (1.0.0rc2 or other 1.x version)

### Describe the bug

I tested the classification performance of the model on a new dataset, unfortunately it reported an error.
```
Traceback (most recent call last):
  File "tools/train.py", line 162, in <module>
    main()
  File "tools/train.py", line 146, in main
    register_all_modules(init_default_scope=False)
  File "/home/s316/workspace/xionggl/mmclassification/mmcls/utils/setup_env.py", line 19, in register_all_modules
    import mmcls.datasets  # noqa: F401,F403
  File "/home/s316/workspace/xionggl/mmclassification/mmcls/datasets/__init__.py", line 15, in <module>
    from .dermnet import Dermnet23
  File "/home/s316/workspace/xionggl/mmclassification/mmcls/datasets/dermnet.py", line 7, in <module>
    from mmcv import FileClient
ImportError: cannot import name 'FileClient' from 'mmcv' (/home/s316/miniconda3/envs/mmcls/lib/python3.8/site-packages/mmcv/__init__.py)
```

### Environment

```
{'sys.platform': 'linux',
 'Python': '3.8.16 (default, Jan 17 2023, 23:13:24) [GCC 11.2.0]',
 'CUDA available': True,
 'numpy_random_seed': 2147483648,
 'GPU 0': 'NVIDIA GeForce RTX 2080 Ti',
 'CUDA_HOME': '/usr/local/cuda-11.1',
 'NVCC': 'Cuda compilation tools, release 11.1, V11.1.74',
 'GCC': 'gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0',
 'PyTorch': '1.12.0',
 'PyTorch compiling details': 'PyTorch built with:\n'
                              '  - GCC 9.3\n'
                              '  - C++ Version: 201402\n'
                              '  - Intel(R) oneAPI Math Kernel Library Version '
                              '2021.4-Product Build 20210904 for Intel(R) 64 '
                              'architecture applications\n'
                              '  - Intel(R) MKL-DNN v2.6.0 (Git Hash '
                              '52b5f107dd9cf10910aaa19cb47f3abf9b349815)\n'
                              '  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n'
                              '  - LAPACK is enabled (usually provided by '
                              'MKL)\n'
                              '  - NNPACK is enabled\n'
                              '  - CPU capability usage: AVX2\n'
                              '  - CUDA Runtime 11.3\n'
                              '  - NVCC architecture flags: '
                              '-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37\n'
                              '  - CuDNN 8.3.2  (built against CUDA 11.5)\n'
                              '  - Magma 2.5.2\n'
                              '  - Build settings: BLAS_INFO=mkl, '
                              'BUILD_TYPE=Release, CUDA_VERSION=11.3, '
                              'CUDNN_VERSION=8.3.2, '
                              'CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, '
                              'CXX_FLAGS= -Wno-deprecated '
                              '-fvisibility-inlines-hidden -DUSE_PTHREADPOOL '
                              '-fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM '
                              '-DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK '
                              '-DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE '
                              '-DEDGE_PROFILER_USE_KINETO -O2 -fPIC '
                              '-Wno-narrowing -Wall -Wextra '
                              '-Werror=return-type '
                              '-Wno-missing-field-initializers '
                              '-Wno-type-limits -Wno-array-bounds '
                              '-Wno-unknown-pragmas -Wno-unused-parameter '
                              '-Wno-unused-function -Wno-unused-result '
                              '-Wno-unused-local-typedefs -Wno-strict-overflow '
                              '-Wno-strict-aliasing '
                              '-Wno-error=deprecated-declarations '
                              '-Wno-stringop-overflow -Wno-psabi '
                              '-Wno-error=pedantic -Wno-error=redundant-decls '
                              '-Wno-error=old-style-cast '
                              '-fdiagnostics-color=always -faligned-new '
                              '-Wno-unused-but-set-variable '
                              '-Wno-maybe-uninitialized -fno-math-errno '
                              '-fno-trapping-math -Werror=format '
                              '-Werror=cast-function-type '
                              '-Wno-stringop-overflow, LAPACK_INFO=mkl, '
                              'PERF_WITH_AVX=1, PERF_WITH_AVX2=1, '
                              'PERF_WITH_AVX512=1, TORCH_VERSION=1.12.0, '
                              'USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, '
                              'USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, '
                              'USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, '
                              'USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, \n',
 'TorchVision': '0.13.0',
 'OpenCV': '4.7.0',
 'MMEngine': '0.5.0',
 'MMClassification': '1.0.0rc5+c7ec630'}
```

### Other information

Here is my config file.
```
_base_ = [
    '../_base_/models/resnet18_dermnet.py', 
    '../_base_/datasets/dermnet_bs64.py',
    '../_base_/schedules/dermnet_bs64_warmup_coslr.py', 
    '../_base_/default_runtime.py'
]
load_from = "/home/s316/workspace/xionggl/mmclassification/checkpoints/resnet18_8xb32_in1k_20210831-fbbb1da6.pth"
randomness = dict(seed=10, deterministic=False)
```
dermnet.py:
```
import warnings
from typing import Callable, Dict, List, Optional, Sequence, Tuple, Union

import mmcv
import numpy as np
from mmcv import FileClient

from .base_dataset import BaseDataset
from .builder import DATASETS
from .custom import CustomDataset

@DATASETS.register_module()
class Dermnet23(CustomDataset):

    IMG_EXTENSIONS = ('.jpg', '.jpeg', '.png', '.ppm', '.bmp', '.pgm', '.tif')
    CLASSES = ['Acne and Rosacea Photos', 'Actinic Keratosis Basal Cell Carcinoma and other Malignant Lesions', 
    'Atopic Dermatitis Photos', 'Bullous Disease Photos', 'Cellulitis Impetigo and other Bacterial Infections',
     'Eczema Photos', 'Exanthems and Drug Eruptions', 'Hair Loss Photos Alopecia and other Hair Diseases',
     'Herpes HPV and other STDs Photos', 'Light Diseases and Disorders of Pigmentation', 
     'Lupus and other Connective Tissue diseases', 'Melanoma Skin Cancer Nevi and Moles',
     'Nail Fungus and other Nail Disease', 'Poison Ivy Photos and other Contact Dermatitis',
     'Psoriasis pictures Lichen Planus and related diseases', 'Scabies Lyme Disease and other Infestations and Bites',
     'Seborrheic Keratoses and other Benign Tumors', 'Systemic Disease',
     'Tinea Ringworm Candidiasis and other Fungal Infections', 'Urticaria Hives',
     'Vascular Tumors', 'Vasculitis Photos', 'Warts Molluscum and other Viral Infections']
    
    def __init__(self,
                 data_prefix: str,
                 pipeline: Sequence = (),
                 classes: Union[str, Sequence[str], None] = None,
                 ann_file: Optional[str] = None,
                 test_mode: bool = False,
                 file_client_args: Optional[dict] = None):
        super().__init__(
            data_prefix=data_prefix,
            pipeline=pipeline,
            classes=classes,
            ann_file=ann_file,
            extensions=self.IMG_EXTENSIONS,
            test_mode=test_mode,
            file_client_args=file_client_args)
```

resnet18_dermnet.py:
```
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='ResNet',
        depth=18,
        num_stages=4,
        out_indices=(3, ),
        style='pytorch'),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=23,
        in_channels=512,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, 5),
    ))
```
dermnet_bs64_warmup_coslr.py
```
optim_wrapper = dict(
    optimizer=dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001))
param_scheduler = [
    dict(
        type='LinearLR',
        start_factor=0.5,
        by_epoch=True,
        begin=0,
        end=30,
        convert_to_iter_based=True,
    ),
    dict(
        type='CosineAnnealingLR',
        T_max=195,
        by_epoch=True,
        begin=30,
        end=90,
    )
]
train_cfg = dict(by_epoch=True, max_epochs=90, val_interval=1)
val_cfg = dict()
test_cfg = dict()
auto_scale_lr = dict(base_batch_size=64)
```

**Comment by Ezra-Yu** [comment]
you are using mmcls `1.x` branch, so you need to install mmengine by run this command 
```
pip install -U openmim
mim install mmegine
```

**Comment by Xglbrilliant** [comment]
> you are using mmcls `1.x` branch, so you need to install mmengine by run this command
> 
> ```
> pip install -U openmim
> mim install mmegine
> ```

I reinstalled according to the document steps and still reported this error, I checked the environment, which already includes mmengine. In addition, I tried to execute a command and found a problem:
![image](https://user-images.githubusercontent.com/95476150/220044733-2ae17442-1610-42f7-87bc-ec3c9472e4b7.png)

**Comment by Ezra-Yu** [comment]
sorry, it is **`mmengine`** not **`mmegine`**.

so run ```mim install mmengine```

**Comment by Xglbrilliant** [comment]
> sorry, it is **`mmengine`** not **`mmegine`**.
> 
> so run `mim install mmengine`

This does not affect, because mmengine has been installed in the environment, even if it is still an error:
![image](https://user-images.githubusercontent.com/95476150/220060097-740a76da-706f-40c1-94de-3214d2269bf0.png)

**Comment by Xglbrilliant** [comment]
I have absolutely no idea what the problem is.

**Comment by Ezra-Yu** [comment]
what in this file `datasets/dermnet.py`

it seems error in this file, which is writed by yourself.

**Comment by Xglbrilliant** [comment]
> what in this file `datasets/dermnet.py`
> 
> it seems error in this file, which is writed by yourself.

Here is my datasets/dermnet.py file：
```
import warnings
from typing import Callable, Dict, List, Optional, Sequence, Tuple, Union

import mmcv
import numpy as np
from mmcv import FileClient

from .base_dataset import BaseDataset
from .builder import DATASETS
from .custom import CustomDataset

@DATASETS.register_module()
class Dermnet23(CustomDataset):

    IMG_EXTENSIONS = ('.jpg', '.jpeg', '.png', '.ppm', '.bmp', '.pgm', '.tif')
    CLASSES = ['Acne and Rosacea Photos', 'Actinic Keratosis Basal Cell Carcinoma and other Malignant Lesions', 
    'Atopic Dermatitis Photos', 'Bullous Disease Photos', 'Cellulitis Impetigo and other Bacterial Infections',
     'Eczema Photos', 'Exanthems and Drug Eruptions', 'Hair Loss Photos Alopecia and other Hair Diseases',
     'Herpes HPV and other STDs Photos', 'Light Diseases and Disorders of Pigmentation', 
     'Lupus and other Connective Tissue diseases', 'Melanoma Skin Cancer Nevi and Moles',
     'Nail Fungus and other Nail Disease', 'Poison Ivy Photos and other Contact Dermatitis',
     'Psoriasis pictures Lichen Planus and related diseases', 'Scabies Lyme Disease and other Infestations and Bites',
     'Seborrheic Keratoses and other Benign Tumors', 'Systemic Disease',
     'Tinea Ringworm Candidiasis and other Fungal Infections', 'Urticaria Hives',
     'Vascular Tumors', 'Vasculitis Photos', 'Warts Molluscum and other Viral Infections']
    
    def __init__(self,
                 data_prefix: str,
                 pipeline: Sequence = (),
                 classes: Union[str, Sequence[str], None] = None,
                 ann_file: Optional[str] = None,
                 test_mode: bool = False,
                 file_client_args: Optional[dict] = None):
        super().__init__(
            data_prefix=data_prefix,
            pipeline=pipeline,
            classes=classes,
            ann_file=ann_file,
            extensions=self.IMG_EXTENSIONS,
            test_mode=test_mode,
            file_client_args=file_client_args)
```

**Comment by Ezra-Yu** [comment]
rm ```from mmcv import FileClient; file_client_args``` related lines

if you want to use ceph, just use like flowing:
```
dataset_cfg = dict(
    type="CustomDataset",
    ann_file = "s3://xx/Dermnet/ann_file.txt",
    data_prefix = "s3://xx/Dermnet/images"
)
```

**Comment by Xglbrilliant** [comment]
> 

Hello, may I ask how to write the custom data format without comment files? I don't see any mention in the documentation.

**Comment by Ezra-Yu** [comment]
https://mmclassification.readthedocs.io/en/latest/tutorials/new_dataset.html#tutorial-3-customize-dataset

**Comment by Xglbrilliant** [comment]
I rewrote the dataset.
```
from typing import Optional, Union

from mmengine.logging import MMLogger

from mmcls.registry import DATASETS
from .categories import CLASSES
from .custom import CustomDataset


@DATASETS.register_module()
class Dermnet23(CustomDataset):

    IMG_EXTENSIONS = ('.jpg', '.jpeg', '.png', '.ppm', '.bmp', '.pgm', '.tif')
    METAINFO = {'classes': CLASSES}

    def __init__(self,
                 ann_file: str = '',
                 metainfo: Optional[dict] = None,
                 data_root: str = '',
                 data_prefix: Union[str, dict] = '',
                 **kwargs):
        kwargs = {'extensions': self.IMG_EXTENSIONS, **kwargs}
        super().__init__(
            ann_file=ann_file,
            metainfo=metainfo,
            data_root=data_root,
            data_prefix=data_prefix,
            **kwargs)
```
 but it seems to have another error:
```
Traceback (most recent call last):
  File "tools/train.py", line 162, in <module>
    main()
  File "tools/train.py", line 158, in main
    runner.train()
  File "/home/s316/miniconda3/envs/mmcls-1x/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1686, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/s316/miniconda3/envs/mmcls-1x/lib/python3.8/site-packages/mmengine/runner/loops.py", line 90, in run
    self.run_epoch()
  File "/home/s316/miniconda3/envs/mmcls-1x/lib/python3.8/site-packages/mmengine/runner/loops.py", line 106, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/s316/miniconda3/envs/mmcls-1x/lib/python3.8/site-packages/mmengine/runner/loops.py", line 122, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/s316/miniconda3/envs/mmcls-1x/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 114, in train_step
    losses = self._run_forward(data, mode='loss')  # type: ignore
  File "/home/s316/miniconda3/envs/mmcls-1x/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 326, in _run_forward
    results = self(**data, mode=mode)
  File "/home/s316/miniconda3/envs/mmcls-1x/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/s316/workspace/xionggl/Experiment/mmclassification/mmcls/models/classifiers/image.py", line 114, in forward
    return self.loss(inputs, data_samples)
  File "/home/s316/workspace/xionggl/Experiment/mmclassification/mmcls/models/classifiers/image.py", line 224, in loss
    return self.head.loss(feats, data_samples)
  File "/home/s316/workspace/xionggl/Experiment/mmclassification/mmcls/models/heads/cls_head.py", line 80, in loss
    losses = self._get_loss(cls_score, data_samples, **kwargs)
  File "/home/s316/workspace/xionggl/Experiment/mmclassification/mmcls/models/heads/cls_head.py", line 95, in _get_loss
    loss = self.loss_module(
  File "/home/s316/miniconda3/envs/mmcls-1x/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/s316/workspace/xionggl/Experiment/mmclassification/mmcls/models/losses/cross_entropy_loss.py", line 201, in forward
    loss_cls = self.loss_weight * self.cls_criterion(
  File "/home/s316/workspace/xionggl/Experiment/mmclassification/mmcls/models/losses/cross_entropy_loss.py", line 32, in cross_entropy
    loss = F.cross_entropy(pred, label, weight=class_weight, reduction='none')
  File "/home/s316/miniconda3/envs/mmcls-1x/lib/python3.8/site-packages/torch/nn/functional.py", line 3014, in cross_entropy
    return torch._C._nn.cross_entropy_
AttributeError: module 'torch._C._nn' has no attribute 'cross_entropy_'
```

**Comment by Ezra-Yu** [comment]
```AttributeError: module 'torch._C._nn' has no attribute 'cross_entropy_'``` this error is about model.

**Comment by Xglbrilliant** [comment]
> `AttributeError: module 'torch._C._nn' has no attribute 'cross_entropy_'` this error is about model. if you want to fine-tune, refer to this [tutorial](https://mmclassification.readthedocs.io/en/latest/tutorials/finetune.html). Maybe you can try to run the example before your modification.

But my model seems to be fine.I changed CrossEntropyLoss to LabelSmoothLoss and it was fine.

**Comment by Ezra-Yu** [comment]
error in `"/home/s316/miniconda3/envs/mmcls-1x/lib/python3.8/site-packages/torch/nn/functional.py"`, i am also confused about that, it seems to be because torch.

**Comment by Xglbrilliant** [comment]
> error in `"/home/s316/miniconda3/envs/mmcls-1x/lib/python3.8/site-packages/torch/nn/functional.py"`, i am also confused about that, it seems to be because torch.

ok, thank you very much for your answer and help.
