### ISSUE TITLE
[Bug] gt labels are not transformed correctly in multi task training 

### ISSUE THREAD

**Issue by ThomaswellY** [open-mmlab/mmclassification#1393]
### 分支

1.x 分支 (1.0.0rc2 或其他 1.x 版本)

### 描述该错误

Hi , i were using the newest mmclassification 1.X，and found a BUG to report to you (or some mistakes i made, and need your helps).  the multi classification were performed well as what 0.2.4 did, but when i used it in multi-task , the BUG appeared.
Under the guide of the project 1.X, The images of the whole datasets are labeled , and the annotation json are prepared.(by the way, there are some differences between your github commits , filed changed records and the codes comments.). the reports on errors are shown below:
03/01 16:13:47 - mmengine - INFO - Load checkpoint from /home/yanghao/project/datasets/pretrain_model/mobilenet_v3_small-8427ecf0.pth
03/01 16:13:47 - mmengine - INFO - Checkpoints will be saved to /home/yanghao/project/mmclassification_1.X/tools/work_dirs/myconfig_multitask.
Traceback (most recent call last):
  File "/home/yanghao/project/mmclassification_1.X/tools/train.py", line 162, in <module>
    main()
  File "/home/yanghao/project/mmclassification_1.X/tools/train.py", line 158, in main
    runner.train()
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1686, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/mmengine/runner/loops.py", line 90, in run
    self.run_epoch()
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/mmengine/runner/loops.py", line 105, in run_epoch
    for idx, data_batch in enumerate(self.dataloader):
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yanghao/project/mmclassification_1.X/mmcls/datasets/multi_task.py", line 316, in __getitem__
    return self.prepare_data(idx)
  File "/home/yanghao/project/mmclassification_1.X/mmcls/datasets/multi_task.py", line 295, in prepare_data
    return self.pipeline(results)
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/mmcv/transforms/wrappers.py", line 87, in transform
    results = t(results)  # type: ignore
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/home/yanghao/project/mmclassification_1.X/mmcls/datasets/transforms/formatting.py", line 93, in transform
    data_sample.set_gt_label(gt_label)
  File "/home/yanghao/project/mmclassification_1.X/mmcls/structures/cls_data_sample.py", line 139, in set_gt_label
    label_data.label = format_label(value)
  File "/home/yanghao/project/mmclassification_1.X/mmcls/structures/cls_data_sample.py", line 38, in format_label
    raise TypeError(f'Type {type(value)} is not an available label type.')
TypeError: Type <class 'dict'> is not an available label type.  

### 环境信息

{'sys.platform': 'linux',
 'Python': '3.8.16 | packaged by conda-forge | (default, Feb  1 2023, '
           '16:01:55) [GCC 11.3.0]',
 'CUDA available': True,
 'numpy_random_seed': 2147483648,
 'GPU 0,1,2,3': 'Tesla P100-PCIE-16GB',
 'CUDA_HOME': '/usr/local/cuda-10.0',
 'NVCC': 'Cuda compilation tools, release 10.0, V10.0.13',
 'GCC': 'gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609',
 'PyTorch': '1.10.0',
 'PyTorch compiling details': 'PyTorch built with:\n'
                              '  - GCC 7.3\n'
                              '  - C++ Version: 201402\n'
                              '  - Intel(R) oneAPI Math Kernel Library Version '
                              '2021.4-Product Build 20210904 for Intel(R) 64 '
                              'architecture applications\n'
                              '  - Intel(R) MKL-DNN v2.2.3 (Git Hash '
                              '7336ca9f055cf1bfa13efb658fe15dc9b41f0740)\n'
                              '  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n'
                              '  - LAPACK is enabled (usually provided by '
                              'MKL)\n'
                              '  - NNPACK is enabled\n'
                              '  - CPU capability usage: AVX512\n'
                              '  - CUDA Runtime 10.2\n'
                              '  - NVCC architecture flags: '
                              '-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37\n'
                              '  - CuDNN 7.6.5\n'
                              '  - Magma 2.5.2\n'
                              '  - Build settings: BLAS_INFO=mkl, '
                              'BUILD_TYPE=Release, CUDA_VERSION=10.2, '
                              'CUDNN_VERSION=7.6.5, '
                              'CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, '
                              'CXX_FLAGS= -Wno-deprecated '
                              '-fvisibility-inlines-hidden -DUSE_PTHREADPOOL '
                              '-fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM '
                              '-DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK '
                              '-DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE '
                              '-DEDGE_PROFILER_USE_KINETO -O2 -fPIC '
                              '-Wno-narrowing -Wall -Wextra '
                              '-Werror=return-type '
                              '-Wno-missing-field-initializers '
                              '-Wno-type-limits -Wno-array-bounds '
                              '-Wno-unknown-pragmas -Wno-sign-compare '
                              '-Wno-unused-parameter -Wno-unused-variable '
                              '-Wno-unused-function -Wno-unused-result '
                              '-Wno-unused-local-typedefs -Wno-strict-overflow '
                              '-Wno-strict-aliasing '
                              '-Wno-error=deprecated-declarations '
                              '-Wno-stringop-overflow -Wno-psabi '
                              '-Wno-error=pedantic -Wno-error=redundant-decls '
                              '-Wno-error=old-style-cast '
                              '-fdiagnostics-color=always -faligned-new '
                              '-Wno-unused-but-set-variable '
                              '-Wno-maybe-uninitialized -fno-math-errno '
                              '-fno-trapping-math -Werror=format '
                              '-Wno-stringop-overflow, LAPACK_INFO=mkl, '
                              'PERF_WITH_AVX=1, PERF_WITH_AVX2=1, '
                              'PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, '
                              'USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, '
                              'USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, '
                              'USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, '
                              'USE_NNPACK=ON, USE_OPENMP=ON, \n',
 'TorchVision': '0.11.0',
 'OpenCV': '4.7.0',
 'MMEngine': '0.6.0',
 'MMClassification': '1.0.0rc5+'}

### 其他信息

The dataset consists of two multi-classification task, which is respectively about 3 classification and 4 classification. 
The dataset follow the construction:
data_output:
                  1. annotation:
                                        1.1 train.json
                                        1.2 val.json
                                        1.3 test.json
                  2.val:
                          a.jpg
                          b.jpg
                          ……  
                  3.test:
                          ……
                  4.train:
                          ……
Here are the configurations parameters:
1.configs/mobilenet_v2/myconfig_multitask.py
_base_ = [
    '../_base_/datasets/mydataset_multiwork.py',
    '../_base_/schedules/imagenet_bs256.py',
    '../_base_/default_runtime.py'
]
# model settings
model = dict(
    type='ImageClassifier',
    backbone=dict(type='MobileNetV3', arch='small'),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='MultiTaskHead',
        task_heads={
            'task1': dict(
                type='StackedLinearClsHead',
                num_classes=3,
                in_channels=576,
                mid_channels = [1024],
                dropout_rate = 0.2,
                act_cfg = dict(type='HSwish'),
                loss = dict(
                    type='CrossEntropyLoss',
                    loss_weight=1.0),
                topk=(1, )
                ),
            'task2': dict(
                type='StackedLinearClsHead',
                num_classes=4,
                in_channels=576,
                mid_channels = [1024],
                dropout_rate = 0.2,
                act_cfg = dict(type='HSwish'),
                loss = dict(
                    type='CrossEntropyLoss',
                    loss_weight=1.0),
                topk=(1, )
                ),
        },
            init_cfg=dict(
                type='Normal', layer='Linear', mean=0., std=0.01, bias=0.),
            )
)
3._base_/datasets/mydataset_multiwork.py
# dataset settings
dataset_type = 'MultiTaskDataset'
data_preprocessor = dict(
    # RGB format normalization parameters
    mean=[123.675, 116.28, 103.53],
    std=[58.395, 57.12, 57.375],
    to_rgb=True, # convert image from BGR to RGB
)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomCrop', crop_size=32, padding=4),
    dict(type='RandomFlip', prob=0.5, direction='horizontal'),
    dict(type='PackClsInputs'),
    # dict(type='FormatMultiTaskLabels'),                             .
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='PackClsInputs'),
]
train_dataloader = dict(
    batch_size=32,
    num_workers=5,
    dataset=dict(
        type="MultiTaskDataset",
        data_root="/home/yanghao/project/datasets/multi_task/data_output/train",
        ann_file="../annotation/train.json",
        pipeline=train_pipeline),
    sampler=dict(type='DefaultSampler', shuffle=True),
)
val_dataloader = dict(
    batch_size=32,
    num_workers=5,
    dataset=dict(
        type="MultiTaskDataset",
        data_root="/home/yanghao/project/datasets/multi_task/data_output/val",
        ann_file="../annotation/val.json",
        pipeline=test_pipeline),
    sampler=dict(type='DefaultSampler', shuffle=True),
)
test_dataloader = dict(
    batch_size=32,
    num_workers=5,
    dataset=dict(
        type="MultiTaskDataset",
        data_root="/home/yanghao/project/datasets/multi_task/data_output/test",
        ann_file="../annotation/test.json",
        pipeline=test_pipeline),
    sampler=dict(type='DefaultSampler', shuffle=True),
)
the_metrics = {
            'task0': [dict(type='Accuracy', topk=(1,3 ))],
            'task1': [dict(type='Accuracy', topk=(1,4))]
        }
val_evaluator = dict(
        type='MultiTasksMetric',
        task_metrics=the_metrics
        )
test_evaluator = val_evaluator

well, the "dict(type='FormatMultiTaskLabels')" in train_pipeline is annotated, otherwise annother report would show as below:
KeyError: "class `MultiTaskDataset` in mmcls/datasets/multi_task.py: 'FormatMultiTaskLabels is not in the transform registry.
I set debug and found the error happend in "elif not isinstance(value, torch.Tensor):" in mmcls/structures/cls_data_sample.py
I guess the class of 'FormatMultiTaskLabels' should work for transforming gt_label value to torch.
I guess, mayber there are several reasons for the BUG:
1. The version of mmclassification i cloned is not the latest version, thus it doesn't contained the class `FormatMultiTaskLabels' which is designed for "Use this to replace `ToTensor`"
2. the modification of "Pipeline FormatMultiTaskLabels + unit tests" has not implemented yet
Last but not least, I wonder where i can find the final version of the user guides to arrange multi-task, containing how to set datasets, pipeline, evaluation metrics, and how to modify the model's head. the docs of "Migration from MMClassification 0.x" seems out of date.
Finally i I have to express my thanks and respect to your team for such great project! if there are childish mistakes i made, please forgive me.
Looking forward to your reply.

**Comment by ThomaswellY** [comment]
@mzr1996 Could you please have a look , thanks alot !

**Comment by mzr1996** [comment]
I think you should use `PackMultiTaskInputs` instead of `PackClsInputs`, like
```python
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomCrop', crop_size=32, padding=4),
    dict(type='RandomFlip', prob=0.5, direction='horizontal'),
    dict(type='PackMultiTaskInputs', multi_task_fields=('gt_label', )),
]
```
And you are right, the docs about multi-task supports are not done now, sorry about it.

**Comment by ThomaswellY** [comment]
> 

Thanks for your appreciate reply ! I have modified the train pipeline as you recommeded, however it still doesn't work. The modified part of the codes and error reports are shown below:
1.mydataset_multiwork.py
……
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomCrop', crop_size=32, padding=4),
    dict(type='RandomFlip', prob=0.5, direction='horizontal'),
    dict(type='PackMultiTaskInputs',
         multi_task_fields=('gt_label',),
         meta_keys=('sample_idx', 'img_path', 'ori_shape', 'img_shape',
                    'scale_factor', 'flip', 'flip_direction')
         )
]
……
2. error reports:
Traceback (most recent call last):
  File "/home/yanghao/project/mmclassification_1.X/tools/train.py", line 162, in <module>
    main()
  File "/home/yanghao/project/mmclassification_1.X/tools/train.py", line 158, in main
    runner.train()
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1686, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/mmengine/runner/loops.py", line 90, in run
    self.run_epoch()
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/mmengine/runner/loops.py", line 106, in run_epoch
    self.run_iter(idx, data_batch)
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/mmengine/runner/loops.py", line 122, in run_iter
    outputs = self.runner.model.train_step(
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/mmengine/model/base_model/base_model.py", line 116, in train_step
    optim_wrapper.update_params(parsed_losses)
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/mmengine/optim/optimizer/optimizer_wrapper.py", line 184, in update_params
    self.backward(loss)
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/mmengine/optim/optimizer/optimizer_wrapper.py", line 208, in backward
    loss.backward(**kwargs)
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/yanghao/anaconda3/envs/mmcls-1.X/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by ThomaswellY** [comment]
@mzr1996 Did i made mistakes in any detail ? I would be very appreicate, if you could offer any further assistance~

**Comment by ThomaswellY** [comment]
@Ezra-Yu Bro Could you please have a look, the BUG has been opened for 1 month.

**Comment by mzr1996** [comment]
Hello, I can't determine what happened according to your error report. It looks like something is wrong with the loss, will it always happen on the first iteration? You can use `--cfg-options default_hooks.logger.interval=1` to print the log on every iteration.

**Comment by Ezra-Yu** [comment]
@ThomaswellY  Does the error related to this [PR](https://github.com/open-mmlab/mmclassification/pull/1426).

**Comment by marouaneamz** [comment]
@mzr1996 @Ezra-Yu  Hey, yes this error exists when we have a full mask so we can't calculate the gradient, I'm trying to correct in this #1426  but I have a problem to complete the training, I think mmcvs are not suitable for all image formats #1427

**Comment by Abdalla981** [comment]
@mzr1996 I'm facing the same issue as @ThomaswellY. After debugging, I found that the error happens during loss calculation in ImageClassifier's loss method. Is there a fix for that?

**Comment by Ezra-Yu** [comment]
@Abdalla981  Can this PR https://github.com/open-mmlab/mmpretrain/pull/1426 help you?

modify this line https://github.com/open-mmlab/mmpretrain/blob/e80418a424aaefb81c95df458216bb3e9af246c4/mmpretrain/models/heads/multi_task_head.py#L25

To:
```
    loss = (inputs[0] * 0).sum()
    return {'loss': loss, 'mask_size': torch.tensor(0.)}
```

**Comment by Ezra-Yu** [comment]
@Abdalla981 Have you solved your problem?

**Comment by Truantboy** [comment]
This seems like a bug in PackMultiTaskInputs
https://github.com/open-mmlab/mmpretrain/blob/e80418a424aaefb81c95df458216bb3e9af246c4/mmpretrain/datasets/transforms/formatting.py#L200-L205
To:
```python
task_results = defaultdict(dict)
for field in self.multi_task_fields:
    if field in results['gt_label']:
        value = results['gt_label'].pop(field)
        task_results[field] = dict(gt_label=value)
```
AND
`data_prefix ` does not work in MultiTaskDataset

**Comment by Abdalla981** [comment]
@Ezra-Yu Sorry for the late reply. Yes, I fixed my issue by ensuring that my custom dataset returns data in the following style:
