### ISSUE TITLE
[Bug] KeyError: 'img' in CustomDataset

### ISSUE THREAD

**Issue by bryanbocao** [open-mmlab/mmclassification#1460]
### Branch

master branch (0.24 or other 0.x version)

### Describe the bug

```
python3 tools/train.py configs/n_cls/dk_CIFAR-10-images_n_cls_8_v0.py
```
```
...
2023-04-06 14:30:45,623 - mmcls - INFO - Start running, host: root@25f32fc9db3c, work_dir: /share/home/brcao/Repos/efficient-ml/mmclassification/work_dir_CIFAR-10-images_n_cls_8_v0
2023-04-06 14:30:45,623 - mmcls - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) StepLrUpdaterHook
(NORMAL      ) CheckpointHook
(LOW         ) EvalHook
(VERY_LOW    ) TextLoggerHook
 --------------------
before_train_epoch:
(VERY_HIGH   ) StepLrUpdaterHook
(LOW         ) IterTimerHook
(LOW         ) EvalHook
(VERY_LOW    ) TextLoggerHook
 --------------------
before_train_iter:
(VERY_HIGH   ) StepLrUpdaterHook
(LOW         ) IterTimerHook
(LOW         ) EvalHook
 --------------------
after_train_iter:
(ABOVE_NORMAL) OptimizerHook
(NORMAL      ) CheckpointHook
(LOW         ) IterTimerHook
(LOW         ) EvalHook
(VERY_LOW    ) TextLoggerHook
 --------------------
after_train_epoch:
(NORMAL      ) CheckpointHook
(LOW         ) EvalHook
(VERY_LOW    ) TextLoggerHook
 --------------------
before_val_epoch:
(LOW         ) IterTimerHook
(VERY_LOW    ) TextLoggerHook
 --------------------
before_val_iter:
(LOW         ) IterTimerHook
 --------------------
after_val_iter:
(LOW         ) IterTimerHook
 --------------------
after_val_epoch:
(VERY_LOW    ) TextLoggerHook
 --------------------
after_run:
(VERY_LOW    ) TextLoggerHook
 --------------------
2023-04-06 14:30:45,624 - mmcls - INFO - workflow: [('train', 1)], max: 300 epochs
2023-04-06 14:30:45,624 - mmcls - INFO - Checkpoints will be saved to /share/home/brcao/Repos/efficient-ml/mmclassification/work_dir_CIFAR-10-images_n_cls_8_v0 by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 205, in <module>
    main()
  File "tools/train.py", line 201, in main
    meta=meta)
  File "/share/home/brcao/Repos/mmclassification/mmcls/apis/train.py", line 233, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/share/home/brcao/Repos/mmclassification/mmcls/datasets/base_dataset.py", line 97, in __getitem__
    return self.prepare_data(idx)
  File "/share/home/brcao/Repos/mmclassification/mmcls/datasets/base_dataset.py", line 91, in prepare_data
    return self.pipeline(results)
  File "/share/home/brcao/Repos/mmclassification/mmcls/datasets/pipelines/compose.py", line 33, in __call__
    data = t(data)
  File "/share/home/brcao/Repos/mmclassification/mmcls/datasets/pipelines/transforms.py", line 102, in __call__
    img = results[key]
KeyError: 'img'
```

### Environment

```
python3 -c "import mmcls.utils;import pprint;pprint.pp(dict(mmcls.utils.collect_env()))"
/usr/local/lib/python3.6/dist-packages/mmcv/__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'pprint' has no attribute 'pp'
```

### Other information

```
configs/n_cls/dk_CIFAR-10-images_n_cls_8_v0.py
```
```
dataset = 'CIFAR-10-images_n_cls_8_v0' # edit
classes = ['airplane', 'automobile', 'cat', 'deer', 'dog', 'frog', 'horse', 'truck'] # edit

_base_ = ['../repvgg/repvgg-B2_4xb64-coslr-120e_in1k.py']

# Model config
model = dict(
    backbone=dict(
    # frozen_stages=2,
    init_cfg=dict(
        type='Normal', # 'Pretrained',
        # checkpoint='https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb32_in1k_20210831-ea4938fc.pth',
        # prefix='backbone',
    )),
    head=dict(num_classes=8),
)

# Dataset config
img_norm_cfg = dict(
    mean=[125.307, 122.961, 113.8575],
    std=[51.5865, 50.847, 51.255],
    to_rgb=False,
)
train_pipeline = [
    dict(type='RandomCrop', size=32, padding=4),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Resize', size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label']),
]
test_pipeline = [
    dict(type='Resize', size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img']),
]
dataset_type = 'CustomDataset' # 'Filelist' # 'CustomDataset'
    
data = dict(
    samples_per_gpu=32,     # Batch size of a single GPU
    workers_per_gpu=2,      # Worker to pre-fetch data for each single GPU
    train=dict(            # train data config
        type=dataset_type,                  # dataset name
        # ann_file='image_list.txt',
        data_prefix='/share/home/brcao/Data/datasets/{}/train'.format(dataset),  # Dataset root, when ann_file does not exist, the category information is automatically obtained from the root folder
        pipeline=train_pipeline,
        ann_file='/share/home/brcao/Data/datasets/{}/meta/train.txt'.format(dataset)),           # train data pipeline
    val=dict(              # val data config
        type=dataset_type,
        data_prefix='/share/home/brcao/Data/datasets/{}/val'.format(dataset),
        ann_file='/share/home/brcao/Data/datasets/{}/meta/val.txt'.format(dataset), 
        # 'data/imagenet/meta/val.txt',   #  ann_file existes, the category information is obtained from file
        pipeline=test_pipeline),
    test=dict(             # test data config
        type=dataset_type,
        data_prefix='/share/home/brcao/Data/datasets/{}/val'.format(dataset),
        ann_file='/share/home/brcao/Data/datasets/{}/meta/val.txt'.format(dataset), 
        # 'data/imagenet/meta/val.txt',
        pipeline=test_pipeline))
evaluation = dict(       # The config to build the evaluation hook, refer to https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/eval_hooks.py#L7 for more details.
    interval=1,          # Evaluation interval
    metric='accuracy')   # Metrics used during evaluation

# Training schedule config
# lr is set for a batch size of 128
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='step', step=[15])
runner = dict(type='EpochBasedRunner', max_epochs=300)

# Config to set the checkpoint hook, Refer to https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/checkpoint.py for implementation.
checkpoint_config = dict(interval=1)    # The save interval is 1
# config to register logger hook
log_config = dict(
    interval=10,                       # Interval to print the log
    hooks=[
        dict(type='TextLoggerHook'),           # The Tensorboard logger is also supported
        # dict(type='TensorboardLoggerHook')
    ])

dist_params = dict(backend='nccl')   # Parameters to setup distributed training, the port can also be set.
log_level = 'INFO'             # The output level of the log.
resume_from = None             # Resume checkpoints from a given path, the training will be resumed from the epoch when the checkpoint's is saved.
workflow = [('train', 1)]      # Workflow for runner. [('train', 1)] means there is only one workflow and the workflow named 'train' is executed once.
work_dir = 'work_dir_' + dataset          # Directory to save the model checkpoints and logs for the current experiments.
```

CustomDataset:
```
CIFAR-10-images_n_cls_8_v0
    |--train/
        |--airplane/*.jpg
        |--automobile/*.jpg
        ...
        |--truck/
            |--9_0000.jpg
            |--9_0001.jpg
          ...
    |--val/
        ...
    |--meta/
        train.txt
        val.txt
```

I have tried both formats:
```train.txt```:
```
...
3_2392.jpg 7
3_2393.jpg 7
3_2394.jpg 7
3_2395.jpg 7
3_2396.jpg 7
3_2397.jpg 7
3_2398.jpg 7
...
```

```train.txt```:
```
...
train/3_2392.jpg 7
train/3_2393.jpg 7
train/3_2394.jpg 7
train/3_2395.jpg 7
train/3_2396.jpg 7
train/3_2397.jpg 7
train/3_2398.jpg 7
...
```

**Comment by bryanbocao** [comment]
```
2023-04-06 17:00:10,650 - mmcls - INFO - Checkpoints will be saved to /share/home/brcao/Repos/efficient-ml/mmclassification/work_dir_CIFAR-10-images_n_cls_8_v0 by HardDiskBackend.
results:  {'img_prefix': '/share/home/brcao/Data/datasets/CIFAR-10-images_n_cls_8_v0/train', 'img_info': {'img': 'train/3_1391.jpg'}, 'gt_label': array(7)}
results:  {'img_prefix': '/share/home/brcao/Data/datasets/CIFAR-10-images_n_cls_8_v0/train', 'img_info': {'img': 'train/1_1072.jpg'}, 'gt_label': array(1)}
results:  {'img_prefix': '/share/home/brcao/Data/datasets/CIFAR-10-images_n_cls_8_v0/train', 'img_info': {'img': 'train/9_4223.jpg'}, 'gt_label': array(3)}
results:  {'img_prefix': '/share/home/brcao/Data/datasets/CIFAR-10-images_n_cls_8_v0/train', 'img_info': {'img': 'train/1_3413.jpg'}, 'gt_label': array(1)}
results:  {'img_prefix': '/share/home/brcao/Data/datasets/CIFAR-10-images_n_cls_8_v0/train', 'img_info': {'img': 'train/3_2020.jpg'}, 'gt_label': array(7)}
Traceback (most recent call last):
  File "tools/train.py", line 205, in <module>
    main()
  File "tools/train.py", line 201, in main
    meta=meta)
  File "/share/home/brcao/Repos/mmclassification/mmcls/apis/train.py", line 233, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/share/home/brcao/Repos/mmclassification/mmcls/datasets/base_dataset.py", line 97, in __getitem__
    return self.prepare_data(idx)
  File "/share/home/brcao/Repos/mmclassification/mmcls/datasets/base_dataset.py", line 91, in prepare_data
    return self.pipeline(results)
  File "/share/home/brcao/Repos/mmclassification/mmcls/datasets/pipelines/compose.py", line 33, in __call__
    data = t(data)
  File "/share/home/brcao/Repos/mmclassification/mmcls/datasets/pipelines/transforms.py", line 103, in __call__
    img = results[key]
KeyError: 'img'
```

Print in https://github.com/open-mmlab/mmclassification/blob/master/mmcls/datasets/pipelines/transforms.py#L100
```
print('\n results: ', results)
```

**Comment by bryanbocao** [comment]
```
results:
 key:  img
 {'img_prefix': '/share/home/brcao/Data/datasets/CIFAR-10-images_n_cls_8_v0/train', 'img_info': {'img': '5_2377.jpg'}, 'gt_label': array(6)}

 results.get(img_info, [img]):  {'img': '5_2377.jpg'}

 key:  img
Traceback (most recent call last):
  File "tools/train.py", line 205, in <module>

 results:  {'img_prefix': '/share/home/brcao/Data/datasets/CIFAR-10-images_n_cls_8_v0/train', 'img_info': {'img': '4_4410.jpg'}, 'gt_label': array(4)}

 results.get(img_info, [img]):  {'img': '4_4410.jpg'}

 key:  img
    main()
  File "tools/train.py", line 201, in main
    meta=meta)
  File "/share/home/brcao/Repos/mmclassification/mmcls/apis/train.py", line 233, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/share/home/brcao/Repos/mmclassification/mmcls/datasets/base_dataset.py", line 97, in __getitem__
    return self.prepare_data(idx)
  File "/share/home/brcao/Repos/mmclassification/mmcls/datasets/base_dataset.py", line 91, in prepare_data
    return self.pipeline(results)
  File "/share/home/brcao/Repos/mmclassification/mmcls/datasets/pipelines/compose.py", line 33, in __call__
    data = t(data)
  File "/share/home/brcao/Repos/mmclassification/mmcls/datasets/pipelines/transforms.py", line 110, in __call__
    img, padding=self.padding, pad_val=self.pad_val)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/image/geometric.py", line 568, in impad
    value=pad_val)
cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'copyMakeBorder'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'
```
```mmcls/datasets/pipelines/transforms.py```
```
def __call__(self, results):
        """
        Args:
            img (ndarray): Image to be cropped.
        """
        print('\n results: ', results)
        print('\n results.get(img_info, [img]): ', results.get('img_info', ['img']))
        # for key in results.get('img_fields', ['img']):
        results_img = results.get('img_info', ['img'])
        for key in results.get('img_info', ['img']):
            print('\n key: ', key)
            img = results_img[key] ## results[key]
```

**Comment by bryanbocao** [comment]
Solved. Will make a pull request and update the documents accordingly.

**Comment by bryanbocao** [comment]
Solved by adding ```dict(type='LoadImageFromFile')``` into train and test pipelines.
```
dataset = 'CIFAR-10-images_n_cls_8_v0' # edit
classes = ['airplane', 'automobile', 'cat', 'deer', 'dog', 'frog', 'horse', 'truck'] # edit

_base_ = ['../repvgg/repvgg-B2_4xb64-coslr-120e_in1k.py']

# Model config
model = dict(
    backbone=dict(
    # frozen_stages=2,
    init_cfg=dict(
        type='Normal', # 'Pretrained',
        # checkpoint='https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb32_in1k_20210831-ea4938fc.pth',
        # prefix='backbone',
    )),
    head=dict(num_classes=8),
)

# Dataset config
img_norm_cfg = dict(
    mean=[125.307, 122.961, 113.8575],
    std=[51.5865, 50.847, 51.255],
    to_rgb=False,
)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomCrop', size=32, padding=4),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Resize', size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']), # keys=['img'], keys=['filename']
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label']) # keys=['img'], keys=['filename']
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']), # keys=['img'], keys=['filename']
    dict(type='Collect', keys=['img']), # keys=['img'], keys=['filename']
]
dataset_type = 'Filelist' # 'Filelist' # 'CustomDataset'
    
data = dict(
    samples_per_gpu=32,     # Batch size of a single GPU
    workers_per_gpu=2,      # Worker to pre-fetch data for each single GPU
    train=dict(            # train data config
        type=dataset_type,                  # dataset name
        # ann_file='image_list.txt',
        data_prefix='/share/home/brcao/Data/datasets/{}/train'.format(dataset),  # Dataset root, when ann_file does not exist, the category information is automatically obtained from the root folder
        pipeline=train_pipeline,
        ann_file='/share/home/brcao/Data/datasets/{}/meta/train.txt'.format(dataset)),           # train data pipeline
    val=dict(              # val data config
        type=dataset_type,
        data_prefix='/share/home/brcao/Data/datasets/{}/val'.format(dataset),
        ann_file='/share/home/brcao/Data/datasets/{}/meta/val.txt'.format(dataset), 
        # 'data/imagenet/meta/val.txt',   #  ann_file existes, the category information is obtained from file
        pipeline=test_pipeline),
#     test=dict(             # test data config
#         type=dataset_type,
#         data_prefix='/share/home/brcao/Data/datasets/{}/val'.format(dataset),
#         ann_file='/share/home/brcao/Data/datasets/{}/meta/val.txt'.format(dataset), 
#         # 'data/imagenet/meta/val.txt',
#         pipeline=test_pipeline),
)
evaluation = dict(       # The config to build the evaluation hook, refer to https://github.com/open-mmlab/mmdetection/blob/master/mmdet/core/evaluation/eval_hooks.py#L7 for more details.
    interval=1,          # Evaluation interval
    metric='accuracy')   # Metrics used during evaluation

# Training schedule config
# lr is set for a batch size of 128
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='step', step=[15])
runner = dict(type='EpochBasedRunner', max_epochs=300)

# Config to set the checkpoint hook, Refer to https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/checkpoint.py for implementation.
checkpoint_config = dict(interval=1)    # The save interval is 1
# config to register logger hook
log_config = dict(
    interval=10,                       # Interval to print the log
    hooks=[
        dict(type='TextLoggerHook'),           # The Tensorboard logger is also supported
        # dict(type='TensorboardLoggerHook')
    ])

dist_params = dict(backend='nccl')   # Parameters to setup distributed training, the port can also be set.
log_level = 'INFO'             # The output level of the log.
resume_from = None             # Resume checkpoints from a given path, the training will be resumed from the epoch when the checkpoint's is saved.
workflow = [('train', 1)]      # Workflow for runner. [('train', 1)] means there is only one workflow and the workflow named 'train' is executed once.
work_dir = 'work_dir/' + dataset          # Directory to save the model checkpoints and logs for the current experiments.
```
