### ISSUE TITLE
[Bug] KeyError: 'Filelist is not in the dataset registry'

### ISSUE THREAD

**Issue by bryanbocao** [open-mmlab/mmclassification#1461]
### Branch

master branch (0.24 or other 0.x version)

### Describe the bug

Following https://mmclassification.readthedocs.io/en/latest/tutorials/new_dataset.html

```
Traceback (most recent call last):
  File "tools/train.py", line 205, in <module>
    main()
  File "tools/train.py", line 178, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/share/home/brcao/Repos/mmclassification/mmcls/datasets/builder.py", line 55, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/utils/registry.py", line 62, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'Filelist is not in the dataset registry'
```

```
import mmcv
import numpy as np

from .builder import DATASETS
from .base_dataset import BaseDataset

@DATASETS.register_module()
class Filelist(BaseDataset):

    def load_annotations(self):
        assert isinstance(self.ann_file, str)

        data_infos = []
        with open(self.ann_file) as f:
            samples = [x.strip().split(' ') for x in f.readlines()]
            for filename, gt_label in samples:
                info = {'img_prefix': self.data_prefix}
                # info['img_info'] = {'filename': filename}
                info['img_info'] = {'img': filename}
                info['gt_label'] = np.array(gt_label, dtype=np.int64)
                data_infos.append(info)
            return data_infos
        
        '''
        data_infos = []
        for img, gt_label in zip(self.imgs, self.gt_labels):
            gt_label = np.array(gt_label, dtype=np.int64)
            info = {'img': img, 'gt_label': gt_label}
            data_infos.append(info)
        return data_infos
        '''
```

### Environment

Didn't work.

**Comment by bryanbocao** [comment]
Solved by adding ```dict(type='LoadImageFromFile')``` into train and test pipelines.
https://github.com/open-mmlab/mmclassification/issues/1460
https://github.com/open-mmlab/mmclassification/issues/1461
https://github.com/open-mmlab/mmclassification/issues/1462
