### ISSUE TITLE
pytorch2onnx.py running error

### ISSUE THREAD

**Issue by QingChuanWS** [open-mmlab/mmclassification#177]
When I use tools/pytorch2onnx.py to export torch model to onnx file, 
I run `python tools/pytorch2onnx.py configs/resnet/resnet18_b16x8_cifar10.py`,
the following error is generated: 
```
Traceback (most recent call last):
  File "tools/pytorch2onnx.py", line 186, in <module>
    verify=args.verify)
  File "tools/pytorch2onnx.py", line 96, in pytorch2onnx
    opset_version=opset_version)
  File "/home/SENSETIME/liuhengyan/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/torch/onnx/__init__.py", line 208, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/SENSETIME/liuhengyan/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/home/SENSETIME/liuhengyan/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 530, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/SENSETIME/liuhengyan/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 366, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/SENSETIME/liuhengyan/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/torch/onnx/utils.py", line 319, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/home/SENSETIME/liuhengyan/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/torch/jit/__init__.py", line 338, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/SENSETIME/liuhengyan/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/SENSETIME/liuhengyan/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/torch/jit/__init__.py", line 426, in forward
    self._force_outplace,
  File "/home/SENSETIME/liuhengyan/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/torch/jit/__init__.py", line 412, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/SENSETIME/liuhengyan/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/torch/nn/modules/module.py", line 720, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/home/SENSETIME/liuhengyan/anaconda3/envs/pytorch1.6/lib/python3.7/site-packages/torch/nn/modules/module.py", line 704, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/SENSETIME/liuhengyan/mmclassification/mmcls/models/classifiers/base.py", line 85, in forward
    return self.forward_test(img, **kwargs)
  File "/home/SENSETIME/liuhengyan/mmclassification/mmcls/models/classifiers/base.py", line 69, in forward_test
    return self.simple_test(imgs[0], **kwargs)
TypeError: simple_test() missing 1 required positional argument: 'img_metas'

```
I found that this parameter is not used by the function simple_test in mmcls/models/classifiers/image.py. What is img_metas used for? 

env: 
pytorch: 1.6, 
python: 3.7.9
mmclassification: 0.9.0

**Comment by shitongliu** [comment]
I have solved this problem by following #157.

in mmcls/models/classifiers/image.py
`def simple_test(self, img, img_metas):` -> `def simple_test(self, img):`

Hope this helps.
