### ISSUE TITLE
Exploding GFLOPs and CUDNN Internal Error

### ISSUE THREAD

**Issue by digantamisra98** [open-mmlab/mmclassification#189]
I have been extensively using MMCLS in my research, mostly using the ResNet models for CIFAR. I was recently trying a custom Convolution operation which had a separate operation pipeline during training (i.e., when `self.training`) and a different operation during `eval` phase. This custom conv was only used to replace the middle/ 2nd convolution in the bottleneck block of ResNets.

Firstly for some reason, the `tools/get_flops.py` script gets the number of parameters to be correct, however blows up the FLOPs for some reason. Here is the output for the same using the `python tools/get_flops.py configs/resnet/resnet50_b16x8_cifar10.py` script:
```
Input shape: (3, 224, 224)
Flops: 27.97 GFLOPs
Params: 9.71 M
```

I tried the exact same operator at the same place in the model definition of ResNet provided by torchvision [here](https://pytorch.org/vision/stable/_modules/torchvision/models/resnet.html#resnet50). And I used [ptflops](https://pypi.org/project/ptflops/) to measure FLOPs and Parameters which provided me accurate results:

```
Computational complexity:       1.86 GMac
Number of parameters:           9.72 M  
```

As you can see `get_flops.py` is reporting a 15x higher FLOPs for some reason even though the FLOP counter in `get_flops.py` is derived from `ptflops` which I used on the torchvision model. 

Additionally, when I try to train the same model using the script: `python tools/train.py configs/resnet/resnet50_b16x8_cifar10.py`, I get the following **CUDNN internal error**:

```
Traceback (most recent call last):
  File "tools/train.py", line 151, in <module>
    main()
  File "tools/train.py", line 147, in main
    meta=meta)
  File "/home/jupyter/mmclassification/mmcls/apis/train.py", line 149, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/jupyter/mmclassification/mmcls/models/classifiers/base.py", line 150, in train_step
    losses = self(**data)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 84, in new_func
    return old_func(*args, **kwargs)
  File "/home/jupyter/mmclassification/mmcls/models/classifiers/base.py", line 93, in forward
    return self.forward_train(img, **kwargs)
  File "/home/jupyter/mmclassification/mmcls/models/classifiers/image.py", line 72, in forward_train
    x = self.extract_feat(img)
  File "/home/jupyter/mmclassification/mmcls/models/classifiers/image.py", line 49, in extract_feat
    x = self.backbone(img)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jupyter/mmclassification/mmcls/models/backbones/resnet_cifar.py", line 77, in forward
    x = res_layer(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jupyter/mmclassification/mmcls/models/backbones/resnet.py", line 321, in forward
    out = _inner_forward(x)
  File "/home/jupyter/mmclassification/mmcls/models/backbones/resnet.py", line 300, in _inner_forward
    out = self.conv1(x)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 396, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.
import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([128, 512, 16, 16], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(512, 128, kernel_size=[1, 1], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()
ConvolutionParams 
    data_type = CUDNN_DATA_FLOAT
    padding = [0, 0, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x55f724e89c60
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 128, 512, 16, 16, 
    strideA = 131072, 256, 16, 1, 
output: TensorDescriptor 0x55f725177530
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 128, 128, 16, 16, 
    strideA = 32768, 256, 16, 1, 
weight: FilterDescriptor 0x55f7210e09e0
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 128, 512, 1, 1, 
Pointer addresses: 
    input: 0x7fa7f4000000
    output: 0x7fa812800000
    weight: 0x7fa8b7389600
Forward algorithm: 5
```

The script provided in the trace above does work fine for me without any issues. 

Machine Specifications:

##### `nvcc --version`: 
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0
```
##### Storage: 100 GB

After researching online, it seems like an memory issue, I even tried setting `torch.backends.cudnn.benchmark = False` in line 68 in the `tools/train.py` file and it gave the same error. To note, I changed the batch size from 16 to 128. It works fine for a normal ResNet-50.

**Comment by LXXXXR** [comment]
Hi @digantamisra98 ,

Sorry for the late reply. 
For the question regarding FLOPs, you are correct that the calculated FLOPs are about 16 times compared to the one in torchvision. That is due the fact that we use a variation of ResNet for CIFAR in config `configs/resnet/resnet50_b16x8_cifar10.py`. Compared to standard ResNet, it uses `kernel_size=3` and `stride=1` in conv1, and does not apply MaxPoolinng after stem. It has been proven to be more efficient than standard ResNet in other public codebase, e.g.,  `https://github.com/kuangliu/pytorch-cifar/blob/master/models/resnet.py`.
However, if you prefer to use the standard one, you may use `ResNet` as backbone rather than `ResNet_CIFAR`. 

As for the CUDNN internal error, I wasn't able to reproduce it so far. I will get back to you if I get anything.

Hope this helps.

**Comment by digantamisra98** [comment]
Got it, thanks for your explanation around the FLOPs concern. 
Oh, that's weird I'm consistently getting that CUDA error in one of my clusters.

**Comment by digantamisra98** [comment]
Closing this issue since it works fine on my cluster now
