### ISSUE TITLE
demo problem

### ISSUE THREAD

**Issue by bingo789** [open-mmlab/mmclassification#356]
when i run:
python demo/image_demo.py demo/demo.JPEG configs/resnet/resnet18_b16x8_cifar10.py checkpoints/resnet18_b16x8_cifar10_20210528-bd6371c8.pth

this problem happen:
Use load_from_local loader
Traceback (most recent call last):
  File "demo/image_demo.py", line 24, in <module>
    main()
  File "demo/image_demo.py", line 18, in main
    result = inference_model(model, args.img)
  File "/home/bingo/anaconda3/envs/pytorch/lib/python3.7/site-packages/mmcls/apis/inference.py", line 85, in inference_model
    pred_score = np.max(scores, axis=1)[0]
  File "<__array_function__ internals>", line 6, in amax
  File "/home/bingo/anaconda3/envs/pytorch/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2734, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/home/bingo/anaconda3/envs/pytorch/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 85, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
TypeError: max() received an invalid combination of arguments - got (out=NoneType, axis=int, ), but expected one of:
 * ()
 * (name dim, bool keepdim)
      didn't match because some of the keywords were incorrect: out, axis
 * (Tensor other)
 * (int dim, bool keepdim)
      didn't match because some of the keywords were incorrect: out, axis

**Comment by mzr1996** [comment]
Sorry, but I cannot reproduce this problem. Can you provide the entire installation information by
```shell
pip list | grep "mmcv\|mmcls"
```

**Comment by bingo789** [comment]
it print like below:
mmcls              0.13.0
mmcv-full          1.3.9

and my code have change to tag v0.13.0

**Comment by bingo789** [comment]
> Sorry, but I cannot reproduce this problem. Can you provide the entire installation information by
> 
> ```shell
> pip list | grep "mmcv\|mmcls"
> ```

it print like below:
mmcls 0.13.0
mmcv-full 1.3.9

and my code have change to tag v0.13.0
