### ISSUE TITLE
Custom Dataset 自定义数据集 KeyError: 'Vedai is not in the dataset registry'

### ISSUE THREAD

**Issue by tjmannn** [open-mmlab/mmclassification#357]
**请问这是什么原因，几个地方都已修改**
# 报错
`````Traceback (most recent call last):
  File "train.py", line 156, in <module>
    main()
  File "train.py", line 131, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/root/anaconda3/envs/mmc/lib/python3.7/site-packages/mmcls/datasets/builder.py", line 37, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/root/anaconda3/envs/mmc/lib/python3.7/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'Vedai is not in the dataset registry'
``````

# 自定义数据集.py内容
`````import os

import numpy as np

from .base_dataset import BaseDataset
from .builder import DATASETS


def has_file_allowed_extension(filename, extensions):
    """Checks if a file is an allowed extension.

    Args:
        filename (string): path to a file

    Returns:
        bool: True if the filename ends with a known image extension
    """
    filename_lower = filename.lower()
    return any(filename_lower.endswith(ext) for ext in extensions)


def find_folders(root):
    """Find classes by folders under a root.

    Args:
        root (string): root directory of folders

    Returns:
        folder_to_idx (dict): the map from folder name to class idx
    """
    folders = [
        d for d in os.listdir(root) if os.path.isdir(os.path.join(root, d))
    ]
    folders.sort()
    folder_to_idx = {folders[i]: i for i in range(len(folders))}
    return folder_to_idx


def get_samples(root, folder_to_idx, extensions):
    """Make dataset by walking all images under a root.

    Args:
        root (string): root directory of folders
        folder_to_idx (dict): the map from class name to class idx
        extensions (tuple): allowed extensions

    Returns:
        samples (list): a list of tuple where each element is (image, label)
    """
    samples = []
    root = os.path.expanduser(root)
    for folder_name in sorted(os.listdir(root)):
        _dir = os.path.join(root, folder_name)
        if not os.path.isdir(_dir):
            continue

        for _, _, fns in sorted(os.walk(_dir)):
            for fn in sorted(fns):
                if has_file_allowed_extension(fn, extensions):
                    path = os.path.join(folder_name, fn)
                    item = (path, folder_to_idx[folder_name])
                    samples.append(item)
    return samples


@DATASETS.register_module()
class Vedai(BaseDataset):
    """`ImageNet <http://www.image-net.org>`_ Dataset.

    This implementation is modified from
    https://github.com/pytorch/vision/blob/master/torchvision/datasets/imagenet.py  # noqa: E501
    """

    IMG_EXTENSIONS = ('.jpg', '.jpeg', '.png', '.ppm', '.bmp', '.pgm', '.tif')
    CLASSES = ['truck', 'tractor', 'camping-car', 'van', 'other']

    def load_annotations(self):
        if self.ann_file is None:
            folder_to_idx = find_folders(self.data_prefix)
            samples = get_samples(
                self.data_prefix,
                folder_to_idx,
                extensions=self.IMG_EXTENSIONS)
            if len(samples) == 0:
                raise (RuntimeError('Found 0 files in subfolders of: '
                                    f'{self.data_prefix}. '
                                    'Supported extensions are: '
                                    f'{",".join(self.IMG_EXTENSIONS)}'))

            self.folder_to_idx = folder_to_idx
        elif isinstance(self.ann_file, str):
            with open(self.ann_file) as f:
                samples = [x.strip().split(' ') for x in f.readlines()]
        else:
            raise TypeError('ann_file must be a str or None')
        self.samples = samples

        data_infos = []
        for filename, gt_label in self.samples:
            info = {'img_prefix': self.data_prefix}
            info['img_info'] = {'filename': filename}
            info['gt_label'] = np.array(gt_label, dtype=np.int64)
            data_infos.append(info)
        return data_infos
`````

# 下面是__init__.py内容
`````from .base_dataset import BaseDataset
from .builder import DATASETS, PIPELINES, build_dataloader, build_dataset
from .cifar import CIFAR10, CIFAR100
from .dataset_wrappers import (ClassBalancedDataset, ConcatDataset,
                               RepeatDataset)
from .imagenet import ImageNet
from .mnist import MNIST, FashionMNIST
from .multi_label import MultiLabelDataset
from .samplers import DistributedSampler
from .voc import VOC
from .vedai import Vedai

__all__ = [
    'BaseDataset', 'ImageNet', 'CIFAR10', 'CIFAR100', 'Vedai', 'MNIST', 'FashionMNIST',
    'VOC', 'MultiLabelDataset', 'build_dataloader', 'build_dataset',
    'DistributedSampler', 'ConcatDataset', 'RepeatDataset',
    'ClassBalancedDataset', 'DATASETS', 'PIPELINES'
]
`````

**Comment by tjmannn** [comment]
#76 我把这个老哥的文件复制了一遍，然后init里添加，试了一下，同样是未注册的错误

**Comment by tjmannn** [comment]
后来我把dataset下ImageNet那个.py里面的CLASSES换成了我要用的几类，直接用ImageNet的这个名字，就不会报错了，很奇怪，之前也用MMDetection，就没有这种情况

**Comment by mzr1996** [comment]
请问你有按照 [开发版本的mmcls安装指南](https://github.com/open-mmlab/mmclassification/blob/master/docs_zh-CN/install.md#%E5%BC%80%E5%8F%91%E7%89%88%E6%9C%AC) 操作吗？

**Comment by tjmannn** [comment]
@mzr1996 感谢回复，果然是没装好，最后一步没弄。。。。

**Comment by LiUzHiAn** [comment]
@tjmannn 

Hi, 

我安装的时候是通过`pip install -e .`的方式, 然后我也自定义了一个类,不过还是报错提示`XXX`没被注册.

你说的没装好是哪一步没弄啊?

**Comment by mzr1996** [comment]
> @tjmannn
> 
> Hi,
> 
> 我安装的时候是通过`pip install -e .`的方式, 然后我也自定义了一个类,不过还是报错提示`XXX`没被注册.
> 
> 你说的没装好是哪一步没弄啊?

请检查自己的是否按照 [自定义数据集教程](https://mmclassification.readthedocs.io/zh_CN/latest/tutorials/new_dataset.html#id4) 操作，如果问题没有解决，请重新提一个issue，你遇到的可能是其他方面的问题。

**Comment by tjmannn** [comment]
@LiUzHiAn 我就是没进行你说的pip这步

**Comment by LiUzHiAn** [comment]
@tjmannn @mzr1996

感谢你们的回复,问题已经解决了,我是在运行的主脚本中加上了这句:
```python
@DATASETS.register_module()
class XXXDataset(BaseDataset):
    pass
```
而且我并不是在`mmcls`项目中添加该源码的,而是在其他的项目文件中动态添加. 因此,也不用更新`mmcls`的`__init__.py`了. 

Anyway, 感谢你们提供的相关信息.

**Comment by bryanbocao** [comment]
> 请问你有按照 [开发版本的mmcls安装指南](https://github.com/open-mmlab/mmclassification/blob/master/docs_zh-CN/install.md#%E5%BC%80%E5%8F%91%E7%89%88%E6%9C%AC) 操作吗？

404

**Comment by bryanbocao** [comment]
> 请问你有按照 [开发版本的mmcls安装指南](https://github.com/open-mmlab/mmclassification/blob/master/docs_zh-CN/install.md#%E5%BC%80%E5%8F%91%E7%89%88%E6%9C%AC) 操作吗？

@mzr1996 Cannot access the link. 404. Thanks!
