### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by wangstone666** [open-mmlab/mmclassification#42]
I got an error when loading dataset.
`Traceback (most recent call last):
  File "tools/train.py", line 157, in <module>
    main()
  File "tools/train.py", line 153, in main
    meta=meta)
  File "/home/jovyan/work/mmclassification/mmcls/apis/train.py", line 117, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
../../data/imagenet/train/Charles_Taylor/4842.jpg
    data.reraise()
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jovyan/work/mmclassification/mmcls/datasets/base_dataset.py", line 46, in __getitem__
    return self.prepare_data(idx)
  File "/home/jovyan/work/mmclassification/mmcls/datasets/base_dataset.py", line 40, in prepare_data
    return self.pipeline(results)
  File "/home/jovyan/work/mmclassification/mmcls/datasets/pipelines/compose.py", line 32, in __call__
    data = t(data)
  File "/home/jovyan/work/mmclassification/mmcls/datasets/pipelines/loading.py", line 56, in __call__
    results['img_shape'] = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'`

It seems that I give the wrong dataset path and the code can't find these images. Therefore I print image name in code when loading dataset( loading.py), but I find that The program is stuck in different places .

for example:
1st:

**......(other image name )
../../data/imagenet/train/Laszlo_Kovacs/7027.jpg**

`
Traceback (most recent call last):
  File "tools/train.py", line 157, in <module>
    main()
  File "tools/train.py", line 153, in main
    meta=meta)
  File "/home/jovyan/work/mmclassification/mmcls/apis/train.py", line 117, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
../../data/imagenet/train/Charles_Taylor/4842.jpg
    data.reraise()
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jovyan/work/mmclassification/mmcls/datasets/base_dataset.py", line 46, in __getitem__
    return self.prepare_data(idx)
  File "/home/jovyan/work/mmclassification/mmcls/datasets/base_dataset.py", line 40, in prepare_data
    return self.pipeline(results)
  File "/home/jovyan/work/mmclassification/mmcls/datasets/pipelines/compose.py", line 32, in __call__
    data = t(data)
  File "/home/jovyan/work/mmclassification/mmcls/datasets/pipelines/loading.py", line 56, in __call__
    results['img_shape'] = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'`

2nd:
**......(other image name)
../../data/imagenet/train/Colin_Powell/4132.jpg**
`Traceback (most recent call last):
  File "tools/train.py", line 157, in <module>
    main()
  File "tools/train.py", line 153, in main
    meta=meta)
  File "/home/jovyan/work/mmclassification/mmcls/apis/train.py", line 117, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 27, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
../../data/imagenet/train/Tim_Henman/8106.jpg
    return self._process_data(data)
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jovyan/work/mmclassification/mmcls/datasets/base_dataset.py", line 46, in __getitem__
    return self.prepare_data(idx)
  File "/home/jovyan/work/mmclassification/mmcls/datasets/base_dataset.py", line 40, in prepare_data
    return self.pipeline(results)
  File "/home/jovyan/work/mmclassification/mmcls/datasets/pipelines/compose.py", line 32, in __call__
    data = t(data)
  File "/home/jovyan/work/mmclassification/mmcls/datasets/pipelines/loading.py", line 56, in __call__
    results['img_shape'] = img.shape
AttributeError: 'NoneType' object has no attribute 'shape'
`

And I have tried read specific picture with mmcv, it works well.
`
filename="../../data/imagenet/train/Steve_Mariucci/248.jpg"
color_type='color'
file_client = mmcv.FileClient()
img_bytes = file_client.get(filename)
img = mmcv.imfrombytes(img_bytes, flag=color_type)
img = img.astype(np.float32)
print(img.shape)
`

I dont know if i do something wrong~ Thank you so much for reading my problem!

**Comment by LJCZhang** [comment]
may be there is something wrong  in the image data

**Comment by Wulx2050** [comment]
> I dont know if i do something wrong~ Thank you so much for reading my problem!

Sometimes there is always some data in the wrong format, so how did you fix it in the end?

**Comment by Wulx2050** [comment]
We first read the data once, if it is empty, it will not be put into the list.

```python
import cv2, os

train_list_txt = "./Data/train_list.txt"
train_data_dir = "./Data/train"

train_data = []
with open(train_list_txt, "r") as f:
    for line in f:
        name, label = line.strip().split('\t')
        if (cv2.imread(os.path.join(train_data_dir, name)) is not None):
            train_data.append([name, label])
        else:
            print(name)
```

**Comment by Wulx2050** [comment]
> We first read the data once, if it is empty, it will not be put into the list.

The format is wrong, re-encode it to jpg/png/other.

```python
import cv2, os
from PIL import Image

train_list_txt = "./Data/train_list.txt"
train_data_dir = "./Data/train"

train_data = []
with open(train_list_txt, "r") as f:
    for line in f:
        name, label = line.strip().split('\t')
        img_path = os.path.join(train_data_dir, name)
        if (cv2.imread(img_path) is not None):
            train_data.append([name, label])
        else:
            print(img_path)
            img = Image.open(img_path).convert("RGB") # re-encode
            img.save(img_path)
            if (cv2.imread(img_path) is not None):
                train_data.append([name, label])
            else:
                print("------You can not see me----------")
```

**Comment by HongQWang** [comment]
> > We first read the data once, if it is empty, it will not be put into the list.
> 
> The format is wrong, re-encode it to jpg/png/other.
> 
> ```python
> import cv2, os
> from PIL import Image
> 
> train_list_txt = "./Data/train_list.txt"
> train_data_dir = "./Data/train"
> 
> train_data = []
> with open(train_list_txt, "r") as f:
>     for line in f:
>         name, label = line.strip().split('\t')
>         img_path = os.path.join(train_data_dir, name)
>         if (cv2.imread(img_path) is not None):
>             train_data.append([name, label])
>         else:
>             print(img_path)
>             img = Image.open(img_path).convert("RGB") # re-encode
>             img.save(img_path)
>             if (cv2.imread(img_path) is not None):
>                 train_data.append([name, label])
>             else:
>                 print("------You can not see me----------")
> ```

Thank you for your reply. However, that was a long time ago. And I don't remember how I solved this problem.
