### ISSUE TITLE
How to enable mixed precesion training

### ISSUE THREAD

**Issue by d-li14** [open-mmlab/mmclassification#43]
Hi @yl-1993 , thanks for the work. could you please show the template use of FP16 training?
I add `fp16=dict(loss_scale=512.)` to the config file, for example:
```python
_base_ = [
    '../_base_/models/resnet50.py', '../_base_/datasets/imagenet_bs32.py',
    '../_base_/schedules/imagenet_bs256.py', '../_base_/default_runtime.py'
]
fp16=dict(loss_scale=512.)
```
but got the following error:
```shell
Traceback (most recent call last):
  File "tools/train.py", line 157, in <module>
    main()
  File "tools/train.py", line 153, in main
    meta=meta)
  File "/mnt/lustre/liduo/mmclassification/mmcls/apis/train.py", line 117, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/mnt/lustre/liduo/.local.pt1.4.0v2/lib/python3.7/sitepackages/mmcv/runner/epoch_based_runner.py", line 122, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/mnt/lustre/liduo/.local.pt1.4.0v2/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 32, in train
    **kwargs)
  File "/mnt/lustre/liduo/.local.pt1.4.0v2/lib/python3.7/site-packages/mmcv/parallel/distributed.py", line 36, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/mnt/lustre/liduo/mmclassification/mmcls/models/classifiers/base.py", line 136, in train_step
    losses = self(**data)
  File "/mnt/lustre/share/platform/env/miniconda3.7/envs/pt1.4.0v2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/lustre/liduo/mmclassification/mmcls/models/classifiers/base.py", line 79, in forward
    return self.forward_train(img, **kwargs)
  File "/mnt/lustre/liduo/mmclassification/mmcls/models/classifiers/image.py", line 55, in forward_train
    x = self.extract_feat(img)
  File "/mnt/lustre/liduo/mmclassification/mmcls/models/classifiers/image.py", line 37, in extract_feat
    x = self.backbone(img)
  File "/mnt/lustre/share/platform/env/miniconda3.7/envs/pt1.4.0v2/lib/python3.7/site-packages/torch/nn/modules/module.py", l$ne 532, in __call__              
    result = self.forward(*input, **kwargs)
  File "/mnt/lustre/liduo/mmclassification/mmcls/models/backbones/resnet.py", line 610, in forward
    x = self.conv1(x)
  File "/mnt/lustre/share/platform/env/miniconda3.7/envs/pt1.4.0v2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/lustre/share/platform/env/miniconda3.7/envs/pt1.4.0v2/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 345, in forward                                                                                                                  
    return self.conv2d_forward(input, self.weight)
  File "/mnt/lustre/share/platform/env/miniconda3.7/envs/pt1.4.0v2/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward                                                                                                           
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same                                                    
```

**Comment by d-li14** [comment]
In addition to modify config files, `self.fp16_enabled = False` should be inserted into the desired modules.
