### ISSUE TITLE
自制数据集无法使用

### ISSUE THREAD

**Issue by singing4you** [open-mmlab/mmclassification#450]
### 描述你遇到的问题

我阅读了 Tutorial 2: Adding New Dataset 的教程 ，想自制一个鱼的数据集。我新建了 `mmcls/datasets/fish.py` 文件，里面有一个`Fish`类（对应教程里的Filelist类），然后也在`mmcls/datasets/__init__.py`里 添加了 Fish，但是最后用的时候，却报错`KeyError: 'Fish is not in the dataset registry'` 这是为啥呀？

### 相关信息 
![image](https://user-images.githubusercontent.com/56928566/133646647-e7291cca-747a-4ac3-9c0b-29a3974a49cc.png)
这是fish.py文件

![image](https://user-images.githubusercontent.com/56928566/133646776-66f97fa6-7161-44db-892c-4227cc6bc2a0.png)
这是__init__.py文件

```
Traceback (most recent call last):
  File "D:\mmclassification-master\tools\train.py", line 181, in <module>
    main()
  File "D:\mmclassification-master\tools\train.py", line 156, in main
    datasets = [build_dataset(cfg.data.train)]
  File "c:\users\hector\mmclassification\mmcls\datasets\builder.py", line 40, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "C:\Users\Hector\AppData\Local\Programs\Python\Python39\lib\site-packages\mmcv\utils\registry.py", line 46, in build_from_cfg
    raise KeyError(
KeyError: 'Fish is not in the dataset registry'
```
这是报错信息

**Comment by singing4you** [comment]
我找到解决方法了 ，方法就是`https://github.com/open-mmlab/mmclassification/issues/357`里说的 ，要安装开发模式
