### ISSUE TITLE
cv2.error: Caught error in DataLoader worker process 0 while training

### ISSUE THREAD

**Issue by junhuplim** [open-mmlab/mmclassification#464]
### Checklist
- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet
Hi all, I am trying to build a simple classifier to my own dataset that I have reformatted to ImageNet format. I am unable to start the training as cv2.error is being thrown. Appreciate any help! :D 

### Post related information
1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
```python
mmcls                             0.15.0
mmcv-full                         1.3.8
torch                             1.7.1+cu101
torchaudio                        0.7.0
torchfile                         0.1.0
torchnet                          0.0.4
torchsummary                      1.5.1
torchvision                       0.8.2+cu101
```

2. Your config file if you modified it or created a new one.
```python
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='VGG', depth=16, norm_cfg=dict(type='BN'), num_classes=788),
    neck=None,
    head=dict(
        type='ClsHead',
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, 5),
    )
)

img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomResizedCrop', size=224, backend='pillow'),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]

test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=(256, -1), backend='pillow'),
    dict(type='CenterCrop', crop_size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]

data = dict(
    samples_per_gpu=4,
    workers_per_gpu=1,
    train=dict(
        type='ImageNet',
        data_prefix='/workspace/jupyter_notebooks/datasets/mmclass/classification/train',
        pipeline=train_pipeline
    ),
    val=dict(
        type='ImageNet',
        data_prefix='/workspace/jupyter_notebooks/datasets/mmclass/classification/val',
        ann_file='/workspace/jupyter_notebooks/datasets/mmclass/classification/val.txt',
        pipeline=test_pipeline
    ),
    test=dict(
        type='ImageNet',
        data_prefix='/workspace/jupyter_notebooks/datasets/mmclass/classification/val',
        ann_file='/workspace/jupyter_notebooks/datasets/mmclass/classification/val.txt',
        pipeline=test_pipeline
))

optimizer = dict(type='SGD', lr=0.025, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)

lr_config = dict(policy='step', step=[30, 60, 90])
runner = dict(type='EpochBasedRunner', max_epochs=1)

checkpoint_config = dict(interval=1)
log_config = dict(
    interval=1,
    hooks=[
        dict(type='TextLoggerHook'),
    ])

dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
    
```
3. Your train log file if you meet the problem during training.
```python
2021-09-27 05:00:22,800 - mmcls - INFO - workflow: [('train', 1)], max: 1 epochs
2021-09-27 05:00:25,201 - mmcls - INFO - Epoch [1][1/5815]      lr: 2.500e-02, eta: 3:37:48, time: 2.248, data_time: 2.111, memory: 1891, loss: 6.5464
2021-09-27 05:00:25,510 - mmcls - INFO - Epoch [1][2/5815]      lr: 2.500e-02, eta: 2:01:14, time: 0.255, data_time: 0.145, memory: 2459, loss: 32.2662
2021-09-27 05:00:25,818 - mmcls - INFO - Epoch [1][3/5815]      lr: 2.500e-02, eta: 1:30:50, time: 0.311, data_time: 0.201, memory: 2459, loss: 27.2174
2021-09-27 05:00:26,125 - mmcls - INFO - Epoch [1][4/5815]      lr: 2.500e-02, eta: 1:15:32, time: 0.306, data_time: 0.197, memory: 2459, loss: 51.4736
2021-09-27 05:00:26,432 - mmcls - INFO - Epoch [1][5/5815]      lr: 2.500e-02, eta: 1:06:22, time: 0.308, data_time: 0.198, memory: 2459, loss: 89.2028
2021-09-27 05:00:26,737 - mmcls - INFO - Epoch [1][6/5815]      lr: 2.500e-02, eta: 1:00:12, time: 0.304, data_time: 0.195, memory: 2459, loss: 104.8386
2021-09-27 05:00:27,039 - mmcls - INFO - Epoch [1][7/5815]      lr: 2.500e-02, eta: 0:55:47, time: 0.303, data_time: 0.196, memory: 2459, loss: 135.9838
2021-09-27 05:00:27,343 - mmcls - INFO - Epoch [1][8/5815]      lr: 2.500e-02, eta: 0:52:29, time: 0.304, data_time: 0.197, memory: 2459, loss: 439.2282
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    main()
  File "train.py", line 176, in main
    meta=meta)
  File "/usr/local/lib/python3.6/dist-packages/mmcls/apis/train.py", line 160, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/mmcls/datasets/base_dataset.py", line 88, in __getitem__
    return self.prepare_data(idx)
  File "/usr/local/lib/python3.6/dist-packages/mmcls/datasets/base_dataset.py", line 82, in prepare_data
    return self.pipeline(results)
  File "/usr/local/lib/python3.6/dist-packages/mmcls/datasets/pipelines/compose.py", line 33, in __call__
    data = t(data)
  File "/usr/local/lib/python3.6/dist-packages/mmcls/datasets/pipelines/loading.py", line 49, in __call__
    img = mmcv.imfrombytes(img_bytes, flag=self.color_type)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/image/io.py", line 236, in imfrombytes
    img = cv2.imdecode(img_np, flag)
cv2.error: OpenCV(4.5.3) /tmp/pip-req-build-9gwtlx3c/opencv/modules/imgcodecs/src/loadsave.cpp:818: error: (-215:Assertion failed) !buf.empty() in function 'imdecode_'
```

4. Other code you modified in the `mmcls` folder.
Have only modified the ImageNet class to my classes:
```python 
@DATASETS.register_module()
class ImageNet(BaseDataset):
    IMG_EXTENSIONS = ('.jpg', '.jpeg', '.png', '.ppm', '.bmp', '.pgm', '.tif')
    CLASSES = get_class()

    def load_annotations(self):
        if self.ann_file is None:
            folder_to_idx = find_folders(self.data_prefix)
            samples = get_samples(
                self.data_prefix,
                folder_to_idx,
                extensions=self.IMG_EXTENSIONS)
            if len(samples) == 0:
                raise (RuntimeError('Found 0 files in subfolders of: '
                                    f'{self.data_prefix}. '
                                    'Supported extensions are: '
                                    f'{",".join(self.IMG_EXTENSIONS)}'))

            self.folder_to_idx = folder_to_idx
        elif isinstance(self.ann_file, str):
            with open(self.ann_file) as f:
                samples = [x.strip().rsplit(' ', 1) for x in f.readlines()]
        else:
            raise TypeError('ann_file must be a str or None')
        self.samples = samples

        data_infos = []
        for filename, gt_label in self.samples:
            info = {'img_prefix': self.data_prefix}
            info['img_info'] = {'filename': filename}
            info['gt_label'] = np.array(gt_label, dtype=np.int64)
            data_infos.append(info)
        return data_infos
```

**Comment by Ezra-Yu** [comment]
It seems that there are corrupted pictures in your data set, please check that all pictures can be read by opencv.

**Comment by junhuplim** [comment]
ah okay that solved the problem. Thank you!

**Comment by U-zzd** [comment]
I also had the same issue, how did you solve it

**Comment by Ezra-Yu** [comment]
@U-zzd  This [`verify_dataset` tool](https://mmclassification.readthedocs.io/en/1.x/useful_tools/verify_dataset.html)(this link is for the 1.x branch) can help you detect broken images.

**Comment by U-zzd** [comment]
thansk you very much, I solve it
