### ISSUE TITLE
[Bug] EpochBasedRunner fails after first epoch

### ISSUE THREAD

**Issue by tall-josh** [open-mmlab/mmclassification#496]
### Describe the bug
I have a custom Dataset  and DataLoader but when I try and run training I get an error after the first epoch. It appears the Dataoader does not reset correctly but I can't figure out why. Below is the stack trace. I Have also got a sample DataLoader and Dataset I created.

```
INFO:mmcls:Epoch [1][12/13]     lr: 1.000e-01, eta: 0:00:04, time: 0.162, data_time: 0.041, memory: 3655, loss: 9.0995
2021-10-20 22:32:34,235 - mmcls - INFO - Saving checkpoint at 1 epochs
INFO:mmcls:Saving checkpoint at 1 epochs
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/users/josh/.pyenv/versions/3.7.9/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/users/josh/.pyenv/versions/3.7.9/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/users/josh/.cache/pypoetry/virtualenvs/highlighter-all-0omwrkG1-py3.7/lib/python3.7/site-packages/torch/utils/data/_utils/p
in_memory.py", line 28, in _pin_memory_loop
    idx, data = r
ValueError: not enough values to unpack (expected 2, got 0)

Traceback (most recent call last):
  File "/home/users/josh/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/users/josh/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/users/josh/repos/hlall/master/predictors/vision/hl_classify/silverclassify/src/silverclassify/__main__.py", line 100, in <m
odule>
    main()
  File "/home/users/josh/.cache/pypoetry/virtualenvs/highlighter-all-0omwrkG1-py3.7/lib/python3.7/site-packages/click/core.py", line 1128
, in __call__
    return self.main(*args, **kwargs)
  File "/home/users/josh/.cache/pypoetry/virtualenvs/highlighter-all-0omwrkG1-py3.7/lib/python3.7/site-packages/click/core.py", line 1053
, in main
    rv = self.invoke(ctx)
  File "/home/users/josh/.cache/pypoetry/virtualenvs/highlighter-all-0omwrkG1-py3.7/lib/python3.7/site-packages/click/core.py", line 1659
, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/users/josh/.cache/pypoetry/virtualenvs/highlighter-all-0omwrkG1-py3.7/lib/python3.7/site-packages/click/core.py", line 1395
, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/users/josh/.cache/pypoetry/virtualenvs/highlighter-all-0omwrkG1-py3.7/lib/python3.7/site-packages/click/core.py", line 754,
 in invoke
    return __callback(*args, **kwargs)
  File "/home/users/josh/repos/hlall/master/predictors/vision/hl_classify/silverclassify/src/silverclassify/_cli/train.py", line 135, in
_train
    validate=validate
  File "/home/users/josh/.cache/pypoetry/virtualenvs/highlighter-all-0omwrkG1-py3.7/lib/python3.7/site-packages/mmcls/apis/train.py", lin
e 159, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/home/users/josh/.cache/pypoetry/virtualenvs/highlighter-all-0omwrkG1-py3.7/lib/python3.7/site-packages/mmcv/runner/epoch_based_r
unner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/users/josh/.cache/pypoetry/virtualenvs/highlighter-all-0omwrkG1-py3.7/lib/python3.7/site-packages/mmcv/runner/epoch_based_r
unner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/users/josh/.cache/pypoetry/virtualenvs/highlighter-all-0omwrkG1-py3.7/lib/python3.7/site-packages/torch/utils/data/dataload
er.py", line 349, in __iter__
    self._iterator._reset(self)
  File "/home/users/josh/.cache/pypoetry/virtualenvs/highlighter-all-0omwrkG1-py3.7/lib/python3.7/site-packages/torch/utils/data/dataload
er.py", line 852, in _reset
    data = self._get_data()
  File "/home/users/josh/.cache/pypoetry/virtualenvs/highlighter-all-0omwrkG1-py3.7/lib/python3.7/site-packages/torch/utils/data/dataload
er.py", line 1029, in _get_data
    raise RuntimeError('Pin memory thread exited unexpectedly')
RuntimeError: Pin memory thread exited unexpectedly

```

### To Reproduce
The command you executed.

- `mock_dataset.py`
```python
from mmcls.datasets.base_dataset import BaseDataset
from mmcls.datasets.builder import DATASETS
import numpy as np
from typing import List, Dict

@DATASETS.register_module("MockDataset")
class MockDataset(BaseDataset):


    def load_annotations(self):
        data_infos = []
        for i in range(100):
            info = {}
            info['img_info'] = {
                    'image_filename': f"image_{i}.jpg",
                    'image_id': i,
                    }
            info['gt_label'] = np.array(i%2, dtype=np.int64)
            data_infos.append(info)
        return data_infos

################################################################################
# Custom Loading from Highlighter
################################################################################

from mmcls.datasets import PIPELINES

@PIPELINES.register_module()
class MockImageLoader(object):

    def __call__(self, results):
        results["img"] = np.ones((500,500,3), dtype=np.uint8)
        return results

```

### Post related information
1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`

- pytorch 1.7.0
- mmcls: 0.14.0
- mmcv-full: 1.3.9

2. Your config file if you modified it or created a new one.
```python
_base_ = [
    'resnet50.py',
    'imagenet_bs256.py', 'default_runtime.py'
]

custom_imports = dict(imports=['datasets.mock_dataset'], allow_failed_imports=False)
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='MockImageLoader'),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='MockImageLoader'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]

dataset_type = 'MockDataset'

data = dict(
    samples_per_gpu=8,
    workers_per_gpu=1,
    train=dict(
        type=dataset_type,
        data_prefix="mock",
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        data_prefix="mock",
        pipeline=test_pipeline),
    test=dict(
        # replace `data/val` with `data/test` for standard test
        type=dataset_type,
        data_prefix="mock",
        pipeline=test_pipeline))
evaluation = dict(interval=1, metric='accuracy')

```

**Comment by Ezra-Yu** [comment]
Update your pytorch to 1.8.0 or Update your code to latest.

refer to https://github.com/open-mmlab/mmclassification/issues/472

fix in https://github.com/open-mmlab/mmclassification/pull/474

**Comment by tall-josh** [comment]
Thanks. Upgrading to Torch 1.8.0 worked for me!

**Comment by tall-josh** [comment]
Can close I guess. :+1:
