### ISSUE TITLE
TypeError: simple_test() got an unexpected keyword argument 'gt_label'

### ISSUE THREAD

**Issue by MingcongCao** [open-mmlab/mmclassification#51]
Hi, we followed the steps given in getting_started.md to train a Resnet-50-based classifier with MNIST, but one issue comes up as follows.

Downloading http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz to data/mnist/train-images-idx3-ubyte.gz
Extracting data/mnist/train-images-idx3-ubyte.gz to data/mnist
Downloading http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz to data/mnist/train-labels-idx1-ubyte.gz
Extracting data/mnist/train-labels-idx1-ubyte.gz to data/mnist
Downloading http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz to data/mnist/t10k-images-idx3-ubyte.gz
Extracting data/mnist/t10k-images-idx3-ubyte.gz to data/mnist
Downloading http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz to data/mnist/t10k-labels-idx1-ubyte.gz
Extracting data/mnist/t10k-labels-idx1-ubyte.gz to data/mnist
/pytorch/torch/csrc/utils/tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.
2020-10-01 01:15:23,434 - mmcls - INFO - Start running, host: root@047e116c429b, work_dir: /SUANFAZU/SUANFAZU/MMClassification/mmclassification-master/run
2020-10-01 01:15:23,434 - mmcls - INFO - workflow: [('train', 1)], max: 20 epochs
2020-10-01 01:15:25,899 - mmcls - INFO - Epoch [1][100/469]	lr: 1.000e-02, eta: 0:03:48, time: 0.025, data_time: 0.022, memory: 43, loss: 1.4555, top-1: 61.9297
2020-10-01 01:15:26,288 - mmcls - INFO - Epoch [1][200/469]	lr: 1.000e-02, eta: 0:02:10, time: 0.004, data_time: 0.002, memory: 43, loss: 0.4446, top-1: 88.0938
2020-10-01 01:15:26,676 - mmcls - INFO - Epoch [1][300/469]	lr: 1.000e-02, eta: 0:01:38, time: 0.004, data_time: 0.002, memory: 43, loss: 0.3176, top-1: 91.1172
2020-10-01 01:15:27,063 - mmcls - INFO - Epoch [1][400/469]	lr: 1.000e-02, eta: 0:01:21, time: 0.004, data_time: 0.002, memory: 43, loss: 0.2701, top-1: 92.3516
2020-10-01 01:15:27,346 - mmcls - INFO - Saving checkpoint at 1 epochs
[                                                  ] 0/10000, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/train.py", line 157, in <module>
    main()
  File "tools/train.py", line 153, in main
    meta=meta)
  File "/SUANFAZU/SUANFAZU/MMClassification/mmclassification-master/mmcls/apis/train.py", line 117, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/usr/local/lib/python3.6/dist-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/SUANFAZU/SUANFAZU/MMClassification/mmclassification-master/mmcls/core/evaluation/eval_hooks.py", line 27, in after_train_epoch
    results = single_gpu_test(runner.model, self.dataloader, show=False)
  File "/SUANFAZU/SUANFAZU/MMClassification/mmclassification-master/mmcls/apis/test.py", line 20, in single_gpu_test
    result = model(return_loss=False, **data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mmcv/parallel/data_parallel.py", line 42, in forward
    return super().forward(*inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/SUANFAZU/SUANFAZU/MMClassification/mmclassification-master/mmcls/models/classifiers/base.py", line 83, in forward
    return self.forward_test(img, **kwargs)
  File "/SUANFAZU/SUANFAZU/MMClassification/mmclassification-master/mmcls/models/classifiers/base.py", line 67, in forward_test
    return self.simple_test(imgs[0], **kwargs)
TypeError: simple_test() got an unexpected keyword argument 'gt_label'

It seems that the training process can be activated but something happened when the checkpoint was saving. Any response will be greatly appreciated.

**Comment by daavoo** [comment]
In the `test_pipeline` of your configuration file, you have to replace:

```
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
```
with:
`    dict(type='Collect', keys=['img'])`

**Comment by MingcongCao** [comment]
> In the `test_pipeline` of your configuration file, you have to replace:
> 
> ```python
>     dict(type='ToTensor', keys=['gt_label']),
>     dict(type='Collect', keys=['img', 'gt_label'])
> ```
> 
> with:
> 
> ```python
>     dict(type='Collect', keys=['img'])
> ```

Thanks a lot.
