### ISSUE TITLE
ClassBalancedDataset: TypeError: iteration over a 0-d array

### ISSUE THREAD

**Issue by AyeshaNirma** [open-mmlab/mmclassification#514]
### Describe the question you meet

I am trying to train a model on my own dataset the format is similar to ImageNet. I am using `ClassBalancedDataset` because my dataset is not balanced. Therefore, I added the field in config file and I get the following error.  

### Post related information

```python
mmclassification/mmcls/datasets/base_dataset.py:77: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  return self.data_infos[idx]['gt_label'].astype(np.int)
Traceback (most recent call last):
  File "tools/train.py", line 181, in <module>
    main()
  File "tools/train.py", line 156, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/home/ubuntu/workspace/mmclassification/mmcls/datasets/builder.py", line 37, in build_dataset
    build_dataset(cfg['dataset'], default_args), cfg['oversample_thr'])
  File "/home/ubuntu/workspace/mmclassification/mmcls/datasets/dataset_wrappers.py", line 121, in __init__
    repeat_factors = self._get_repeat_factors(dataset, oversample_thr)
  File "/home/ubuntu/workspace/mmclassification/mmcls/datasets/dataset_wrappers.py", line 140, in _get_repeat_factors
    cat_ids = set(self.dataset.get_cat_ids(idx))
TypeError: iteration over a 0-d array
```

Below is my config file 
```python
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(3, ),
        style='pytorch'),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=1000,
        in_channels=2048,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, 5)))
dataset_type = 'ImageNet'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=(256, -1)),
    dict(type='CenterCrop', crop_size=224),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=(256, -1)),
    dict(type='CenterCrop', crop_size=224),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='ClassBalancedDataset',
        oversample_thr=0.001,
        dataset=dict(
            type='ImageNet',
            data_prefix='data/my-dataset',
            pipeline=[
                dict(type='LoadImageFromFile'),
                dict(type='Resize', size=(256, -1)),
                dict(type='CenterCrop', crop_size=224),
                dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
                dict(
                    type='Normalize',
                    mean=[123.675, 116.28, 103.53],
                    std=[58.395, 57.12, 57.375],
                    to_rgb=True),
                dict(type='ImageToTensor', keys=['img']),
                dict(type='ToTensor', keys=['gt_label']),
                dict(type='Collect', keys=['img', 'gt_label'])
            ])),
    val=dict(
        type='ImageNet',
        data_prefix='data/my-dataset',
        ann_file='data/my-dataset-test/test.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=(256, -1)),
            dict(type='CenterCrop', crop_size=224),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ]),
    test=dict(
        type='ImageNet',
        data_prefix='data/my-dataset',
        ann_file='data/my-dataset-test/test.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=(256, -1)),
            dict(type='CenterCrop', crop_size=224),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ]))
evaluation = dict(interval=1, metric='accuracy')
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(policy='step', step=[30, 60, 90])
runner = dict(type='EpochBasedRunner', max_epochs=1000)
checkpoint_config = dict(interval=1)
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
work_dir = './work_dirs/res_50_5'
gpu_ids = range(0, 1)
`

**Comment by mzr1996** [comment]
Hello, did you modify the `ImageNet` dataset class?

**Comment by AyeshaNirma** [comment]
```python
print(mmcls.__version__)
0.15.0
```

No, did not do any modification in Imagenet dataset class, could you please suggest me what to modify ? I thought it is inherited from `basedataset` so did not modify anything.

**Comment by mzr1996** [comment]
This is a bug and we will fix it later.
Here is a quick fix, modify this file:
https://github.com/open-mmlab/mmclassification/blob/29f512156c526df6748da97d1a8b55879cdabf9e/mmcls/datasets/base_dataset.py#L67-L77
to
```python
     def get_cat_ids(self, idx): 
         """Get category id by index. 
  
         Args: 
             idx (int): Index of data. 
  
         Returns: 
             int: Image category of specified index. 
         """ 
  
         return [int(self.data_infos[idx]['gt_label'])]
```

**Comment by AyeshaNirma** [comment]
It works. Thanks.
