### ISSUE TITLE
Can't draw(or vis) the structure of ResNet(depth=50, deep_stem=True)

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#532]
Hi, dear authors!
Sorry to bother you.
I tried to vis the structure of ResNet(depth=50, deep_stem=True) in tensorboardX. But it didn't work.
Here is the code:
```
from mmcls.models.backbones import ResNet
import torch
from tensorboardX import SummaryWriter

img = torch.rand(1, 3, 512, 512).cuda()

net = ResNet(depth=50, deep_stem=True, out_indices=(3, ))

net = net.cuda()
net.eval()
outputs = net.forward(img)

for output in outputs:
    print(output.shape)

with SummaryWriter(comment='ResNet50') as w:
    w.add_graph(net, input_to_model=img, verbose=False)
```

Error came:
```
Traceback (most recent call last):
  File "/media/gpuservice/DATA/Processing/Ubuntu/core/mmlab/mmclassification/exp.py", line 74, in <module>
    w.add_graph(net, input_to_model=img, verbose=False)
  File "/home/gpuservice/anaconda3/envs/mmlab/lib/python3.7/site-packages/tensorboardX/writer.py", line 945, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose))
  File "/home/gpuservice/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 286, in graph
    trace = torch.jit.trace(model, args)
  File "/home/gpuservice/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/home/gpuservice/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/jit/_trace.py", line 928, in trace_module
    module = make_module(mod, _module_class, _compilation_unit)
  File "/home/gpuservice/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/jit/_trace.py", line 549, in make_module
    elif torch._jit_internal.module_has_exports(mod):
  File "/home/gpuservice/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/_jit_internal.py", line 505, in module_has_exports
    item = getattr(mod, name)
  File "/home/gpuservice/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'ResNet' object has no attribute 'norm1'

Process finished with exit code 1
```

However, It was OK when I set `deep_stem=False`.
Could you tell me how to solve it? 
Thank you!

**Comment by Ezra-Yu** [comment]
there is no error in my experiment.
what is your environment?   use shell `pip list | grep "torch\|mmcv\|mmcls`

![image](https://user-images.githubusercontent.com/18586273/141411984-12759a33-4aff-4210-a89d-4b8c256e6f15.png)

**Comment by zhongqiu1245** [comment]
```
mmcls                         0.16.0                /media/gpuservice/DATA/Processing/Ubuntu/core/mmlab/mmclassification
mmcv                          1.3.14
mmcv-full                     1.3.14
torch                         1.7.0
torchaudio                    0.7.0a0+ac17b64
torchsummaryX                 1.3.0
torchvision                   0.8.0
```

**Comment by Ezra-Yu** [comment]
can you try torch >= 1.8 and the latest version mmcv-full.

**Comment by zhongqiu1245** [comment]
I will try later.
Thank you in advance.
