### ISSUE TITLE
Error caught during inference

### ISSUE THREAD

**Issue by d-li14** [open-mmlab/mmclassification#55]
Hi, after upgrading to the latest commit on master, when I use slurm_train.sh or slurm_test.sh on multiple nodes, the test process throws some errors.

For evaluation after training an epoch (on 8 machines, each with 8 GPUs), the error says
```shell
[>>>>>>>>>>>>>>>>>>>>>>>] 50048/50000, 1028.7 task/s, elapsed: 49s, ETA:     0s
Traceback (most recent call last):
  File "tools/train.py", line 157, in <module>
    main()
  File "tools/train.py", line 153, in main
    meta=meta)
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/train.py", line 117, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/mnt/lustre/lid/mmcv/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/mnt/lustre/lid/mmcv/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/mnt/lustre/lid/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/mnt/lustre/lid/mmclassification/mmcls/core/evaluation/eval_hooks.py", line 74, in after_train_epoch
    self.evaluate(runner, results)
  File "/mnt/lustre/lid/mmclassification/mmcls/core/evaluation/eval_hooks.py", line 32, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/mnt/lustre/lid/mmclassification/mmcls/datasets/base_dataset.py", line 86, in evaluate
    assert len(gt_labels) == num_imgs
AssertionError
```

For only inference on multiple nodes, the error says

```shell
[>>>>>>>>>>>>>>>>>>>>>>>] 50000/50000, 260.8 task/s, elapsed: 192s, ETA:     0sTraceback (most recent call last):    [140/166]
Traceback (most recent call last):
  File "tools/test.py", line 122, in <module>
Traceback (most recent call last):
  File "tools/test.py", line 122, in <module>
  File "tools/test.py", line 122, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "tools/test.py", line 122, in <module>
Traceback (most recent call last):
  File "tools/test.py", line 122, in <module>
  File "tools/test.py", line 122, in <module>
Traceback (most recent call last):
  File "tools/test.py", line 122, in <module>
  File "tools/test.py", line 122, in <module>
    main()
  File "tools/test.py", line 84, in main
    main()
  File "tools/test.py", line 84, in main
    main()
  File "tools/test.py", line 84, in main
    main()
  File "tools/test.py", line 84, in main
    main()
  File "tools/test.py", line 84, in main
    main()
  File "tools/test.py", line 84, in main
    main()
  File "tools/test.py", line 84, in main
    main()
  File "tools/test.py", line 84, in main
    main()
  File "tools/test.py", line 84, in main
    main()
  File "tools/test.py", line 84, in main
    main()
  File "tools/test.py", line 84, in main
    main()
  File "tools/test.py", line 84, in main
    args.gpu_collect)
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/test.py", line 75, in multi_gpu_test
    args.gpu_collect)
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/test.py", line 75, in multi_gpu_test
    args.gpu_collect)
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/test.py", line 75, in multi_gpu_test
    args.gpu_collect)
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/test.py", line 75, in multi_gpu_test
    args.gpu_collect)
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/test.py", line 75, in multi_gpu_test
    args.gpu_collect)
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/test.py", line 75, in multi_gpu_test
    args.gpu_collect)
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/test.py", line 75, in multi_gpu_test
    args.gpu_collect)
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/test.py", line 75, in multi_gpu_test
    results = collect_results_cpu(results, len(dataset), tmpdir)
    results = collect_results_cpu(results, len(dataset), tmpdir)
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/test.py", line 99, in collect_results_cpu
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/test.py", line 99, in collect_results_cpu
    results = collect_results_cpu(results, len(dataset), tmpdir)
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/test.py", line 99, in collect_results_cpu
    results = collect_results_cpu(results, len(dataset), tmpdir)
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/test.py", line 99, in collect_results_cpu
    results = collect_results_cpu(results, len(dataset), tmpdir)
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/test.py", line 99, in collect_results_cpu
    results = collect_results_cpu(results, len(dataset), tmpdir)
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/test.py", line 99, in collect_results_cpu
    results = collect_results_cpu(results, len(dataset), tmpdir)
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/test.py", line 99, in collect_results_cpu
    results = collect_results_cpu(results, len(dataset), tmpdir)
  File "/mnt/lustre/lid/mmclassification/mmcls/apis/test.py", line 99, in collect_results_cpu
    mmcv.dump(result_part, osp.join(tmpdir, f'part_{rank}.pkl'))
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/io.py", line 80, in dump
    mmcv.dump(result_part, osp.join(tmpdir, f'part_{rank}.pkl'))
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/io.py", line 80, in dump
    mmcv.dump(result_part, osp.join(tmpdir, f'part_{rank}.pkl'))
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/io.py", line 80, in dump
    mmcv.dump(result_part, osp.join(tmpdir, f'part_{rank}.pkl'))
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/io.py", line 80, in dump
    mmcv.dump(result_part, osp.join(tmpdir, f'part_{rank}.pkl'))
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/io.py", line 80, in dump
    mmcv.dump(result_part, osp.join(tmpdir, f'part_{rank}.pkl'))
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/io.py", line 80, in dump
    mmcv.dump(result_part, osp.join(tmpdir, f'part_{rank}.pkl'))
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/io.py", line 80, in dump
    handler.dump_to_path(obj, file, **kwargs)
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/handlers/pickle_handler.py", line 26, in dump_to_path
    handler.dump_to_path(obj, file, **kwargs)
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/handlers/pickle_handler.py", line 26, in dump_to_path
    handler.dump_to_path(obj, file, **kwargs)
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/handlers/pickle_handler.py", line 26, in dump_to_path
    mmcv.dump(result_part, osp.join(tmpdir, f'part_{rank}.pkl'))
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/io.py", line 80, in dump
    handler.dump_to_path(obj, file, **kwargs)
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/handlers/pickle_handler.py", line 26, in dump_to_path
    handler.dump_to_path(obj, file, **kwargs)
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/handlers/pickle_handler.py", line 26, in dump_to_path
    handler.dump_to_path(obj, file, **kwargs)
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/handlers/pickle_handler.py", line 26, in dump_to_path
    handler.dump_to_path(obj, file, **kwargs)
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/handlers/pickle_handler.py", line 26, in dump_to_path
    handler.dump_to_path(obj, file, **kwargs)
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/handlers/pickle_handler.py", line 26, in dump_to_path
    obj, filepath, mode='wb', **kwargs)
    obj, filepath, mode='wb', **kwargs)
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/handlers/base.py", line 24, in dump_to_path
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/handlers/base.py", line 24, in dump_to_path
    obj, filepath, mode='wb', **kwargs)
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/handlers/base.py", line 24, in dump_to_path
    obj, filepath, mode='wb', **kwargs)
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/handlers/base.py", line 24, in dump_to_path
    obj, filepath, mode='wb', **kwargs)
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/handlers/base.py", line 24, in dump_to_path
    obj, filepath, mode='wb', **kwargs)
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/handlers/base.py", line 24, in dump_to_path
    obj, filepath, mode='wb', **kwargs)
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/handlers/base.py", line 24, in dump_to_path
    obj, filepath, mode='wb', **kwargs)
  File "/mnt/lustre/lid/mmcv/mmcv/fileio/handlers/base.py", line 24, in dump_to_path
    with open(filepath, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpbarrmwij/part_10.pkl'
    with open(filepath, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpbarrmwij/part_11.pkl'
    with open(filepath, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpbarrmwij/part_12.pkl'
    with open(filepath, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpbarrmwij/part_8.pkl'
    with open(filepath, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpbarrmwij/part_14.pkl'
    with open(filepath, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpbarrmwij/part_13.pkl'
    with open(filepath, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpbarrmwij/part_15.pkl'
    with open(filepath, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpbarrmwij/part_9.pkl'
```

**Comment by yl-1993** [comment]
@d-li14 Thanks for reporting and sorry for the late reply.

The first error can be fixed after https://github.com/open-mmlab/mmclassification/pull/69 is merged. For the second one, please add `--gpu_collect` when test/inference on multiple machines.

**Comment by d-li14** [comment]
@yl-1993 I have already fixed the two problems. Anyway, many thanks for fixing the master branch.
