### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'data'

### ISSUE THREAD

**Issue by little-rice-2020** [open-mmlab/mmclassification#558]
Traceback (most recent call last):
  File "tools/test.py", line 219, in <module>
    main()
  File "tools/test.py", line 126, in main
    cfg.data.test.test_mode = True
  File "/home/user01/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.pye 507, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/user01/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/utils/config.pye 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'data'

**Comment by RDXiaoLu** [comment]
怎么解决的？
