### ISSUE TITLE
When I'm following the tutorial, after input these words, i received 'BlockingInput' object has no attribute 'figure'

### ISSUE THREAD

**Issue by guangminglftg** [open-mmlab/mmclassification#566]
[here is the conmmand]

python demo/image_demo.py demo/demo.JPEG configs/resnet/resnet50_b32x8_imagenet.py \   https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb32_in1k_20210831-ea4938fc.pth

[here is the error]

Traceback (most recent call last):
  File "demo/image_demo.py", line 25, in <module>
    main()
  File "demo/image_demo.py", line 21, in main
    show_result_pyplot(model, args.img, result)
  File "/home/ubuntu/anaconda3/envs/mmclassification/lib/python3.7/site-packages/mmcls/apis/inference.py", line 119, in show_result_pyplot
    wait_time=wait_time)
  File "/home/ubuntu/anaconda3/envs/mmclassification/lib/python3.7/site-packages/mmcls/models/classifiers/base.py", line 213, in show_result
    out_file=out_file)
  File "/home/ubuntu/anaconda3/envs/mmclassification/lib/python3.7/site-packages/mmcls/core/visualization/image.py", line 325, in imshow_infos
    out_file=out_file)
  File "/home/ubuntu/anaconda3/envs/mmclassification/lib/python3.7/site-packages/mmcls/core/visualization/image.py", line 277, in put_img_infos
    self.wait_continue(timeout=wait_time)
  File "/home/ubuntu/anaconda3/envs/mmclassification/lib/python3.7/site-packages/mmcls/core/visualization/image.py", line 138, in wait_continue
    key_press = self.blocking_input(n=1, timeout=0)
  File "/home/ubuntu/anaconda3/envs/mmclassification/lib/python3.7/site-packages/matplotlib/blocking_input.py", line 86, in __call__
    if self.figure.canvas.manager:
AttributeError: 'BlockingInput' object has no attribute 'figure'

**Comment by mzr1996** [comment]
That's a known issue, it's caused by a bug of new version matplotlib, which refers to https://github.com/matplotlib/matplotlib/pull/21791
I will fix it later, please roll back the matplotlib temporarily.
```shell
pip install matplotlib==3.4.3
```

**Comment by guangminglftg** [comment]
thank u !




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmclassification"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 上午10:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmclassification] When I'm following the tutorial, after input these words, i received 'BlockingInput' object has no attribute 'figure' (Issue #566)





 
That's a known issue, it's caused by a bug of new version matplotlib, which refers to matplotlib/matplotlib#21791
 I will fix it later, please roll back the matplotlib temporarily.
 pip install matplotlib==3.4.3
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
