### ISSUE TITLE
[Bug]torch==1.7.0 依然出现pytorch2torchscript对ResNeSt进行编译错误，ModuleAttributeError: 'ResNeSt' object has no attribute 'norm1

### ISSUE THREAD

**Issue by binity** [open-mmlab/mmclassification#615]
Traceback (most recent call last):
  File "tools/deployment/pytorch2torchscript.py", line 139, in <module>
    verify=args.verify)
  File "tools/deployment/pytorch2torchscript.py", line 67, in pytorch2torchscript
    trace_model = torch.jit.trace(model, img_list[0])
  File "/home/admin/.local/lib/python3.6/site-packages/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/home/admin/.local/lib/python3.6/site-packages/torch/jit/_trace.py", line 928, in trace_module
    module = make_module(mod, _module_class, _compilation_unit)
  File "/home/admin/.local/lib/python3.6/site-packages/torch/jit/_trace.py", line 560, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/home/admin/.local/lib/python3.6/site-packages/torch/jit/_trace.py", line 1040, in __init__
    submodule, TracedModule, _compilation_unit=None
  File "/home/admin/.local/lib/python3.6/site-packages/torch/jit/_trace.py", line 549, in make_module
    elif torch._jit_internal.module_has_exports(mod):
  File "/home/admin/.local/lib/python3.6/site-packages/torch/_jit_internal.py", line 505, in module_has_exports
    item = getattr(mod, name)
  File "/home/admin/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'ResNeSt' object has no attribute 'norm1'

运行环境：
pytorch1.7.0 mmcv 1.3.8 mmcls 0.15.0

**Comment by Ezra-Yu** [comment]
There is indeed such a problem under torch1.7.0, We are looking for where the problem is.

it seems that  resnest can be  converted successfully in higher versions of mmcv, mmcls, torch, like below:
```
mmcls                             0.18.0            
mmcv                              1.4.1
torch                             1.9.0
torchaudio                        0.9.0a0+33b2469
torchvision                       0.10.0
```
the resnest  has no difference with latest mmcls.

**Comment by mzr1996** [comment]
It's an upstream bug from PyTorch.
Although PyTorch has supported property after 1.7.0, there is a bug when the property is not accessible, which refers to https://github.com/pytorch/pytorch/pull/50680
In ResNeSt, the `deep_stem` is used but the `norm1` property still exists.
A simple fix is removing the [`norm1` property in ResNet](https://github.com/open-mmlab/mmclassification/blob/131d8c6296caf56cfb3928632b35a80380e4ce98/mmcls/models/backbones/resnet.py#L529-L531) and [`norm2` property in BottleNeck](https://github.com/open-mmlab/mmclassification/blob/131d8c6296caf56cfb3928632b35a80380e4ce98/mmcls/models/backbones/resnet.py#L221-L223), or upgrade your PyTorch to 1.8
