### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by zunction** [open-mmlab/mmclassification#635]
### Checklist
- I have searched related issues but cannot get the expected help. yes
- I have read related documents and don't know what to do. yes

### Describe the question you meet

Installation of mmcls using mim run into error. I have previously been able to install mmcls and mmdet using mim successfully. While trying to setup a new enviroment with seaborn, with the following conda environment setup procedure:

```
conda create -n percep -c conda-forge scikit-learn python=3.7
conda activate percep
conda install jupyter notebook matplotlib tqdm seaborn
conda install pytorch torchvision -c pytorch
conda install pytorch cudatoolkit=10.1 torchvision -c pytorch
pip install openmim
mim install mmcls
mim install mmdet
``` 

I ran into the error below:

```
(perception) [root@SUTD-hpc-gn3 ~]# mim install mmcls
/root/anaconda3/envs/perception/site-packages/_distutils_hack/__init__.py:36: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
installing mmcls from https://github.com/open-mmlab/mmclassification.git.
Cloning into '/tmp/tmpoiu90u1p/mmclassification'...
remote: Enumerating objects: 5321, done.
remote: Counting objects: 100% (249/249), done.
remote: Compressing objects: 100% (200/200), done.
remote: Total 5321 (delta 92), reused 125 (delta 49), pack-reused 5072
Receiving objects: 100% (5321/5321), 8.98 MiB | 3.61 MiB/s, done.
Resolving deltas: 100% (3443/3443), done.
Note: checking out '7dfc9e4a8508c260d2cf2f2e011e3c486a593b62'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

installing dependency: mmcv-full
Traceback (most recent call last):
  File "/root/anaconda3/envs/perception/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/root/anaconda3/envs/perception/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/envs/perception/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/envs/perception/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/anaconda3/envs/perception/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda3/envs/perception/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/root/anaconda3/envs/perception/site-packages/mim/commands/install.py", line 107, in cli
    is_editable=is_editable)
  File "/root/anaconda3/envs/perception/site-packages/mim/commands/install.py", line 206, in install
    is_yes, is_user_dir, is_install_master)
  File "/root/anaconda3/envs/perception/site-packages/mim/commands/install.py", line 541, in install_from_github
    is_user_dir=is_user_dir)
  File "/root/anaconda3/envs/perception/site-packages/mim/commands/install.py", line 460, in install_from_repo
    install_dependencies(dependencies, timeout, is_yes, is_user_dir)
  File "/root/anaconda3/envs/perception/site-packages/mim/commands/install.py", line 381, in install_dependencies
    is_user_dir=is_user_dir)
  File "/root/anaconda3/envs/perception/site-packages/mim/commands/install.py", line 181, in install
    find_url = infer_find_url(target_pkg)
  File "/root/anaconda3/envs/perception/site-packages/mim/commands/install.py", line 279, in infer_find_url
    torch_v, cuda_v = get_torch_cuda_version()
  File "/root/anaconda3/envs/perception/site-packages/mim/utils/utils.py", line 331, in get_torch_cuda_version
    raise err
  File "/root/anaconda3/envs/perception/site-packages/mim/utils/utils.py", line 329, in get_torch_cuda_version
    import torch
  File "/root/anaconda3/envs/perception/site-packages/torch/__init__.py", line 218, in <module>
    ''').strip()) from None
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.

```

### Post related information
1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
NA
2. Your config file if you modified it or created a new one.
NA
3. Your train log file if you meet the problem during training.
NA
4. Other code you modified in the `mmcls` folder.
NA

**Comment by Ezra-Yu** [comment]
It seems that you don't install `torch` in your environment successfully.

please run `pip list | grep "mmcv\|mmcls\|^torch"`

**Comment by zunction** [comment]
The output of the command is
```
torch                         1.7.0
torchvision                   0.8.1
```

**Comment by mzr1996** [comment]
Is the problem solved?
