### ISSUE TITLE
怎么训练低于5类的自定义数据集？

### ISSUE THREAD

**Issue by CNcq** [open-mmlab/mmclassification#667]
我修改了模型配置：
# model settings
model = dict(
    type='ImageClassifier',
    backbone=dict(type='MobileNetV2', widen_factor=1.0),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=4,
        in_channels=1280,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1,),
    ))
优化器选择如下：
# optimizer
optimizer = dict(type='SGD', lr=0.045, momentum=0.9, weight_decay=0.00004)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='step', gamma=0.98, step=1)
runner = dict(type='EpochBasedRunner', max_epochs=300)

控制台输出如下：
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 150/150, 160.1 task/s, elapsed: 1s, ETA:     0sTraceback (most recent call last):
  File "tools/train.py", line 183, in <module>
    main()
  File "tools/train.py", line 179, in main
    meta=meta)
  File "/home/s4027/桌面/mmclassification/mmcls/apis/train.py", line 202, in train_model
    runner.run(data_loaders, cfg.workflow,topk=cfg.model.head.topk)
  File "/home/s4027/anaconda3/envs/mml/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 128, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/s4027/anaconda3/envs/mml/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 54, in train
    self.call_hook('after_train_epoch')
  File "/home/s4027/anaconda3/envs/mml/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/s4027/anaconda3/envs/mml/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 267, in after_train_epoch
    self._do_evaluate(runner)
  File "/home/s4027/anaconda3/envs/mml/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 273, in _do_evaluate
    key_score = self.evaluate(runner, results)
  File "/home/s4027/anaconda3/envs/mml/lib/python3.7/site-packages/mmcv/runner/hooks/evaluation.py", line 362, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "/home/s4027/桌面/mmclassification/mmcls/datasets/base_dataset.py", line 164, in evaluate
    acc = accuracy(results, gt_labels, topk=topk)
  File "/home/s4027/桌面/mmclassification/mmcls/models/losses/accuracy.py", line 115, in accuracy
    res = accuracy_torch(pred, target, topk, thrs)
  File "/home/s4027/桌面/mmclassification/mmcls/models/losses/accuracy.py", line 59, in accuracy_torch
    pred_score, pred_label = pred.topk(maxk, dim=1)
RuntimeError: selected index k out of range

在模型中定义了topk=1,但是模型依旧使用了top5的默认参数传入pred.topk()
请问这个是由于什么引起的？

**Comment by mzr1996** [comment]
Indeed, it's a confusing place.
The argument `topk` in the head is used to calculate accuracy on the training batch.
Your error is caused by the EvaluateHook which is used to calculate metrics on the validation dataset.
To modify the default `topk` options in evaluation, please modify/add the `evaluation` cfg as 
```python
evaluation = dict(interval=1, metric='accuracy', metric_options={'topk': 1})
```

**Comment by CNcq** [comment]
This successfully solved my confusion. Thank you for your answer.

**Comment by xxx0320** [comment]
I have also encountered the same problem. May I ask which file "evaluation CFG" refers to

**Comment by CNcq** [comment]
> I have also encountered the same problem. May I ask which file "evaluation CFG" refers to

config/_base_/datasets/{your datasets config}.py

**Comment by clw5180** [comment]
> Indeed, it's a confusing place. The argument `topk` in the head is used to calculate accuracy on the training batch. Your error is caused by the `EvalHook` which is used to calculate metrics on the validation dataset. To modify the default `topk` options in evaluation, please modify/add the `evaluation` cfg as
> 
> ```python
> evaluation = dict(interval=1, metric='accuracy', metric_options={'topk': 1})
> ```

thanks big old!
