### ISSUE TITLE
Errors ouccer for multi gpus training

### ISSUE THREAD

**Issue by rainylt** [open-mmlab/mmclassification#771]
I'm using 8 K80 gpus in one node, and I can successfully train the model with a single gpu.
When I try to  train resnet50 with 8 gpus, this error happened:

The command I use: 'bash tools/dist_train.sh configs/resnet/resnet50_b16x8_cifar100.py 8'
```
/mnt/xfs1/home/liangtian/anaconda3_1/envs/mmcls/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
usage: train.py [-h] [--work-dir WORK_DIR] [--resume-from RESUME_FROM]
                [--no-validate]
                [--device DEVICE | --gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...]
                | --gpu-id GPU_ID] [--seed SEED] [--diff-seed]
                [--deterministic]
                [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local-rank LOCAL_RANK]
                config
train.py: error: unrecognized arguments: --local_rank=7
usage: train.py [-h] [--work-dir WORK_DIR] [--resume-from RESUME_FROM]
                [--no-validate]
                [--device DEVICE | --gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...]
                | --gpu-id GPU_ID] [--seed SEED] [--diff-seed]
                [--deterministic]
                [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local-rank LOCAL_RANK]
                config
train.py: error: unrecognized arguments: --local_rank=2
usage: train.py [-h] [--work-dir WORK_DIR] [--resume-from RESUME_FROM]
                [--no-validate]
                [--device DEVICE | --gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...]
                | --gpu-id GPU_ID] [--seed SEED] [--diff-seed]
                [--deterministic]
                [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local-rank LOCAL_RANK]
                config
train.py: error: unrecognized arguments: --local_rank=3
usage: train.py [-h] [--work-dir WORK_DIR] [--resume-from RESUME_FROM]
                [--no-validate]
                [--device DEVICE | --gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...]
                | --gpu-id GPU_ID] [--seed SEED] [--diff-seed]
                [--deterministic]
                [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local-rank LOCAL_RANK]
                config
train.py: error: unrecognized arguments: --local_rank=0
usage: train.py [-h] [--work-dir WORK_DIR] [--resume-from RESUME_FROM]
                [--no-validate]
                [--device DEVICE | --gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...]
                | --gpu-id GPU_ID] [--seed SEED] [--diff-seed]
                [--deterministic]
                [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local-rank LOCAL_RANK]
                config
usage: train.py [-h] [--work-dir WORK_DIR] [--resume-from RESUME_FROM]
                [--no-validate]
                [--device DEVICE | --gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...]
                | --gpu-id GPU_ID] [--seed SEED] [--diff-seed]
                [--deterministic]
                [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local-rank LOCAL_RANK]
                config
train.py: error: unrecognized arguments: --local_rank=6
train.py: error: unrecognized arguments: --local_rank=4
usage: train.py [-h] [--work-dir WORK_DIR] [--resume-from RESUME_FROM]
                [--no-validate]
                [--device DEVICE | --gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...]
                | --gpu-id GPU_ID] [--seed SEED] [--diff-seed]
                [--deterministic]
                [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local-rank LOCAL_RANK]
                config
train.py: error: unrecognized arguments: --local_rank=1
usage: train.py [-h] [--work-dir WORK_DIR] [--resume-from RESUME_FROM]
                [--no-validate]
                [--device DEVICE | --gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...]
                | --gpu-id GPU_ID] [--seed SEED] [--diff-seed]
                [--deterministic]
                [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local-rank LOCAL_RANK]
                config
train.py: error: unrecognized arguments: --local_rank=5
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 56772) of binary: /mnt/xfs1/home/liangtian/anaconda3_1/envs/mmcls/bin/python
Traceback (most recent call last):
  File "/mnt/xfs1/home/liangtian/anaconda3_1/envs/mmcls/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/xfs1/home/liangtian/anaconda3_1/envs/mmcls/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/xfs1/home/liangtian/anaconda3_1/envs/mmcls/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/mnt/xfs1/home/liangtian/anaconda3_1/envs/mmcls/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/mnt/xfs1/home/liangtian/anaconda3_1/envs/mmcls/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/mnt/xfs1/home/liangtian/anaconda3_1/envs/mmcls/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/mnt/xfs1/home/liangtian/anaconda3_1/envs/mmcls/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/xfs1/home/liangtian/anaconda3_1/envs/mmcls/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-04-07_18:08:41
  host      : node001.cm.cluster
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 56773)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2022-04-07_18:08:41
  host      : node001.cm.cluster
  rank      : 2 (local_rank: 2)
  exitcode  : 2 (pid: 56774)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2022-04-07_18:08:41
  host      : node001.cm.cluster
  rank      : 3 (local_rank: 3)
  exitcode  : 2 (pid: 56775)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2022-04-07_18:08:41
  host      : node001.cm.cluster
  rank      : 4 (local_rank: 4)
  exitcode  : 2 (pid: 56776)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2022-04-07_18:08:41
  host      : node001.cm.cluster
  rank      : 5 (local_rank: 5)
  exitcode  : 2 (pid: 56777)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2022-04-07_18:08:41
  host      : node001.cm.cluster
  rank      : 6 (local_rank: 6)
  exitcode  : 2 (pid: 56778)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2022-04-07_18:08:41
  host      : node001.cm.cluster
  rank      : 7 (local_rank: 7)
  exitcode  : 2 (pid: 56779)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-04-07_18:08:41
  host      : node001.cm.cluster
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 56772)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by mzr1996** [comment]
Sorry, some recently modification cause this bug.
Please modify the below line
https://github.com/open-mmlab/mmclassification/blob/5a67bc8a1aefd5493732b8f6ab10ee8c04839773/tools/train.py#L76
to
```python
    parser.add_argument('--local_rank', type=int, default=0) 
```

**Comment by rainylt** [comment]
> 

Thank you very much, it was successfully solved!

**Comment by kalikhademi** [comment]
I have the same error and although I changed the line you mentioned I still have this problem. Could you please help me?
