### ISSUE TITLE
Train problem

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmclassification#78]
**RuntimeError: mat1 dim 1 must match mat2 dim 0**

Traceback (most recent call last):
  File "tools/train.py", line 157, in <module>
    main()
  File "tools/train.py", line 153, in main
    meta=meta)
  File "/media/shuozhang/DATA/Processing/OFFICE/deeplearning/mmlab/mmclassification/mmcls/apis/train.py", line 133, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/home/shuozhang/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/shuozhang/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/shuozhang/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/shuozhang/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/media/shuozhang/DATA/Processing/OFFICE/deeplearning/mmlab/mmclassification/mmcls/models/classifiers/base.py", line 140, in train_step
    losses = self(**data)
  File "/home/shuozhang/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/media/shuozhang/DATA/Processing/OFFICE/deeplearning/mmlab/mmclassification/mmcls/models/classifiers/base.py", line 83, in forward
    return self.forward_train(img, **kwargs)
  File "/media/shuozhang/DATA/Processing/OFFICE/deeplearning/mmlab/mmclassification/mmcls/models/classifiers/image.py", line 58, in forward_train
    loss = self.head.forward_train(x, gt_label)
  File "/media/shuozhang/DATA/Processing/OFFICE/deeplearning/mmlab/mmclassification/mmcls/models/heads/linear_head.py", line 54, in forward_train
    cls_score = self.fc(x)
  File "/home/shuozhang/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shuozhang/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/shuozhang/anaconda3/envs/mmlab/lib/python3.7/site-packages/torch/nn/functional.py", line 1674, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0

Could you tell me what's going on？How can I fix it?

**Comment by zhongqiu1245** [comment]
I got it, the num_class was wrong
