### ISSUE TITLE
Questions about designing my own data processing pipeline

### ISSUE THREAD

**Issue by EstherJinyan** [open-mmlab/mmclassification#784]
Hello, I have a problem when I design my own data processing pipeline, could you please take a look？

I want to add an additional mask channel based on the input three-channel image, and the data also needs to be color transformed and flipped, but these operations will affect the mask channel, so my approach is to first perform color transformation on the three-channel image, and then the three-channel and mask channels are flipped at the same time, and finally the processed results are merged into a four-channel image to go to the next step. But the following error occurred during training, what is going on?
```
Traceback (most recent call last):
  _File "tools/train.py", line 194, in <module>
    main()
  File "tools/train.py", line 190, in main
    meta=meta)
  File "/run/ljy/satellite_imagery/research/mmclassification/mmcls/apis/train.py", line 192, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/dockerdata/weimei/env/miniconda3/envs/py37/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/dockerdata/weimei/env/miniconda3/envs/py37/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/dockerdata/weimei/env/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/dockerdata/weimei/env/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/dockerdata/weimei/env/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/dockerdata/weimei/env/miniconda3/envs/py37/lib/python3.7/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/dockerdata/weimei/env/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/dockerdata/weimei/env/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/dockerdata/weimei/env/miniconda3/envs/py37/lib/python3.7/site-packages/mmcv/parallel/collate.py", line 84, in collate
    return default_collate(batch)
  File "/dockerdata/weimei/env/miniconda3/envs/py37/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 180, in default_collate
    raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>_
```

The main modifications I made are as follows:

config.py:
```python
dataset_type = 'GtWithContour_Cls6'
img_norm_cfg = dict(mean=[123.675, 116.28, 103.53, 128], std=[58.395, 57.12, 57.375, 1.0], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageWIthContour', add_mask_flag=True),
    dict(type='ColorJitter', brightness=0.5, contrast=0.5, saturation=0.5, prob=0.5),
    dict(type='RandomFlip', flip_prob=0.5, direction='vertical'),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='MergeImg'),  # 合并mask通道MergeImg
    dict(type='Resize', size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label']),
]
```

mmcls/datasets/pipelines/loading.py
```python
    class LoadImageWIthContour(object):
        def __init__(self, to_float32=False, color_type='color', file_client_args=dict(backend='disk'),
                     add_mask_flag=False):
            self.to_float32 = to_float32
            self.color_type = color_type
            self.file_client_args = file_client_args.copy()
            self.file_client = None
            self.add_mask_flag = add_mask_flag

        def __call__(self, results):
            if self.file_client is None:
                self.file_client = mmcv.FileClient(**self.file_client_args)
            if results['img_prefix'] is not None:
                filename = osp.join(results['img_prefix'], results['img_info']['filename'])
            else:
                filename = results['img_info']['filename']
            img_bytes = self.file_client.get(filename)
            img = mmcv.imfrombytes(img_bytes, flag=self.color_type)
            if self.to_float32:
                img = img.astype(np.float32)
            contour = results['contour']
            h, w = img.shape[:2]
            if contour is None:
                min_val = 1
                contour = [[min_val, min_val], [min_val, h - min_val], [w - min_val, h - min_val],
                           [w - min_val, min_val]]  # 四个点
                contour = np.array(contour)
            another_channel = None
            if self.add_mask_flag is True:  # 增加一个通道
                mask = np.zeros((h, w, 1), np.uint8)
                cv2.fillPoly(mask, [contour], 255)
                another_channel = mask

            results['filename'] = filename
            results['ori_filename'] = results['img_info']['filename']
            results['img'] = img
            results['another_channel'] = another_channel
            results['img_shape'] = img.shape
            results['ori_shape'] = img.shape
            num_channels = 1 if len(img.shape) < 3 else img.shape[2]
            results['img_norm_cfg'] = dict(
                mean=np.zeros(num_channels, dtype=np.float32),
                std=np.ones(num_channels, dtype=np.float32),
                to_rgb=False)
            return results
```

mmcls/datasets/pipelines/transforms.py
```python
class RandomFlip(object):
    def __call__(self, results):
        """Call function to flip image.

        Args:
            results (dict): Result dict from loading pipeline.

        Returns:
            dict: Flipped results, 'flip', 'flip_direction' keys are added into
                result dict.
        """
        flip = True if np.random.rand() < self.flip_prob else False
        results['flip'] = flip
        results['flip_direction'] = self.direction
        if results['flip']:
            # flip image
            for key in results.get('img_fields', ['img']):
                results[key] = mmcv.imflip(results[key], direction=results['flip_direction'])
            # flip mask
            if results['another_channel'] is not None:
                results['another_channel'] = mmcv.imflip(results['another_channel'], direction=results['flip_direction'])
        return results 
```

mmcls/datasets/pipelines/formatting.py
```python
@PIPELINES.register_module()
class MergeImg(object):
    def __init__(self):
        pass

    def __call__(self, results):
        img = results['img']
        another_channel = results['another_channel']
        assert another_channel is not None
        img = np.c_[img, another_channel]
        results['img'] = img
```

**Comment by mzr1996** [comment]
Looks you forget to return `results` in the `__call__` method of `MergeImg` class

**Comment by EstherJinyan** [comment]
Thank you very much!
