### ISSUE TITLE
RuntimeError: mat1 dim 1 must match mat2 dim 0 

### ISSUE THREAD

**Issue by yz-ju** [open-mmlab/mmclassification#797]
When I train vgg-16-BN model with my dataset of 2 classes, I encount the error as follws:

2022-04-22 18:51:36,703 - mmcls - INFO - workflow: [('train', 1)], max: 24 epochs
2022-04-22 18:51:36,703 - mmcls - INFO - Checkpoints will be saved to /public/home/2017010075/04Model_mmclass/CNN-01-VGG/VGG-16-BN/train/logs by HardDiskBackend.
Traceback (most recent call last):
  File "train.py", line 194, in <module>
    main()
  File "train.py", line 182, in main
    train_model(
  File "/public/home/2017010075/model/mmclassification/mmcls/apis/train.py", line 222, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/public/home/2017010075/anaconda3/envs/mmclass/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/public/home/2017010075/anaconda3/envs/mmclass/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/public/home/2017010075/anaconda3/envs/mmclass/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "/public/home/2017010075/anaconda3/envs/mmclass/lib/python3.8/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/public/home/2017010075/model/mmclassification/mmcls/models/classifiers/base.py", line 139, in train_step
    losses = self(**data)
  File "/public/home/2017010075/anaconda3/envs/mmclass/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/public/home/2017010075/anaconda3/envs/mmclass/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/public/home/2017010075/model/mmclassification/mmcls/models/classifiers/base.py", line 83, in forward
    return self.forward_train(img, **kwargs)
  File "/public/home/2017010075/model/mmclassification/mmcls/models/classifiers/image.py", line 134, in forward_train
    x = self.extract_feat(img)
  File "/public/home/2017010075/model/mmclassification/mmcls/models/classifiers/image.py", line 104, in extract_feat
    x = self.backbone(img)
  File "/public/home/2017010075/anaconda3/envs/mmclass/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/public/home/2017010075/model/mmclassification/mmcls/models/backbones/vgg.py", line 162, in forward
    x = self.classifier(x)
  File "/public/home/2017010075/anaconda3/envs/mmclass/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/public/home/2017010075/anaconda3/envs/mmclass/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/public/home/2017010075/anaconda3/envs/mmclass/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/public/home/2017010075/anaconda3/envs/mmclass/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/public/home/2017010075/anaconda3/envs/mmclass/lib/python3.8/site-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 dim 1 must match mat2 dim 0

I just changed the num_classes from 1000 to 2 in the config file. The details of the config file are as following:

model = dict(
    type='ImageClassifier',
    backbone=dict(type='VGG', depth=16, num_classes=2),
    neck=None,
    head=dict(
        type='ClsHead',
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, 5)))
dataset_type = 'Landslide2'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=1024, backend='pillow'),
    dict(type='RandomFlip', flip_prob=0.0, direction='horizontal'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=1024, backend='pillow'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
IMG_DIR_TRAIN = '/public/home/2017010075/04Data_ImgClass_LoessLandslide/13-dataset/trainval-size1024'
IMG_DIR_VAL = '/public/home/2017010075/04Data_ImgClass_LoessLandslide/13-dataset/trainval-size1024'
IMG_DIR_TEST = '/public/home/2017010075/04Data_ImgClass_LoessLandslide/13-dataset/test-size1024'
ANN_DIR_TRAIN = '/public/home/2017010075/04Data_ImgClass_LoessLandslide/13-dataset/label0.01/label0.01_train.txt'
ANN_DIR_VAL = '/public/home/2017010075/04Data_ImgClass_LoessLandslide/13-dataset/label0.01/label0.01_val.txt'
ANN_DIR_TEST = '/public/home/2017010075/04Data_ImgClass_LoessLandslide/13-dataset/label0.01/label0.01_test.txt'
data = dict(
    samples_per_gpu=8,
    workers_per_gpu=2,
    train=dict(
        type='Landslide2',
        data_prefix=
        '/public/home/2017010075/04Data_ImgClass_LoessLandslide/13-dataset/trainval-size1024',
        ann_file=
        '/public/home/2017010075/04Data_ImgClass_LoessLandslide/13-dataset/label0.01/label0.01_train.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=1024, backend='pillow'),
            dict(type='RandomFlip', flip_prob=0.0, direction='horizontal'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='ToTensor', keys=['gt_label']),
            dict(type='Collect', keys=['img', 'gt_label'])
        ]),
    val=dict(
        type='Landslide2',
        data_prefix=
        '/public/home/2017010075/04Data_ImgClass_LoessLandslide/13-dataset/trainval-size1024',
        ann_file=
        '/public/home/2017010075/04Data_ImgClass_LoessLandslide/13-dataset/label0.01/label0.01_val.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=1024, backend='pillow'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ]),
    test=dict(
        type='Landslide2',
        data_prefix=
        '/public/home/2017010075/04Data_ImgClass_LoessLandslide/13-dataset/test-size1024',
        ann_file=
        '/public/home/2017010075/04Data_ImgClass_LoessLandslide/13-dataset/label0.01/label0.01_test.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=1024, backend='pillow'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ]))
evaluation = dict(interval=1, metric_options=dict(topk=1))
optimizer = dict(type='SGD', lr=0.001, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(policy='step', step=[24])
runner = dict(type='EpochBasedRunner', max_epochs=24)
checkpoint_config = dict(interval=1)
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = '../../pretrained/vgg16_bn_batch256_imagenet_20210208-7e55cd29.pth'
resume_from = None
workflow = [('train', 1)]
work_dir = './logs/'
gpu_ids = [3]

What can I do to solve the problem?

**Comment by Ezra-Yu** [comment]
try to debug by yourself and know the size before this [line](https://github.com/open-mmlab/mmclassification/blob/6beac5060f0c1d57141642dba77c19c9ed6b3873/mmcls/models/backbones/vgg.py#L161)

**Comment by tonysy** [comment]
This issue will be closed as it is inactive, feel free to re-open it if necessary.
