### ISSUE TITLE
Error when i change dataset in swin tranformer tutorial

### ISSUE THREAD

**Issue by vothaianh1997** [open-mmlab/mmclassification#803]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/content/mmclassification-0.22.0/mmclassification-0.22.0/mmcls/datasets/imagenet.py", line 1034, in __init__
    file_client_args=file_client_args)
  File "/content/mmclassification-0.22.0/mmclassification-0.22.0/mmcls/datasets/custom.py", line 170, in __init__
    test_mode=test_mode)
  File "/content/mmclassification-0.22.0/mmclassification-0.22.0/mmcls/datasets/base_dataset.py", line 51, in __init__
    self.data_infos = self.load_annotations()
  File "/content/mmclassification-0.22.0/mmclassification-0.22.0/mmcls/datasets/custom.py", line 220, in load_annotations
    for filename, gt_label in samples:
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 194, in <module>
    main()
  File "tools/train.py", line 190, in main
    meta=meta)
  File "/content/mmclassification-0.22.0/mmclassification-0.22.0/mmcls/apis/train.py", line 171, in train_model
    val_dataset = build_dataset(cfg.data.val, dict(test_mode=True))
  File "/content/mmclassification-0.22.0/mmclassification-0.22.0/mmcls/datasets/builder.py", line 50, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
ValueError: ImageNet: not enough values to unpack (expected 2, got 1)

**Comment by Ezra-Yu** [comment]
It seems that labels are not being loaded correctly.

here is an example to use [swin](https://drive.google.com/file/d/12Aa88pVrerVGUMOADfW_3cNGymFSXqd_/view?usp=sharing)

**Comment by vothaianh1997** [comment]
pls give me link colab with vgg19 (fine tuning)
