### ISSUE TITLE
FileNotFoundError: CustomDataset: [Errno 2] No such file or directory: 'data/imagenet/meta/val.txt'

### ISSUE THREAD

**Issue by grapefruitL** [open-mmlab/mmclassification#889]
我是用以下配置进行自定义数据集训练：
```
_base_ = [
    '../_base_/models/resnet18.py',
    '../_base_/datasets/imagenet_bs32.py', '../_base_/default_runtime.py'
]

# Model config
model = dict(
    backbone=dict(
        frozen_stages=2,
        init_cfg=dict(
            type='Pretrained',
            checkpoint='https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb32_in1k_20210831-ea4938fc.pth',
            prefix='backbone',
        )),
    head=dict(num_classes=6),
)

# Dataset config
img_norm_cfg = dict(
    mean=[125.307, 122.961, 113.8575],
    std=[51.5865, 50.847, 51.255],
    to_rgb=False,
)
train_pipeline = [
    dict(type='RandomCrop', size=32, padding=4),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Resize', size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label']),
]
test_pipeline = [
    dict(type='Resize', size=224),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img']),
]
# data = dict(
#     samples_per_gpu=128,
#     train=dict(pipeline=train_pipeline),
#     val=dict(pipeline=test_pipeline),
#     test=dict(pipeline=test_pipeline),
# )

dataset_type = 'CustomDataset'
classes = ['0', '1', '2', '3', '4', '5']  # The category names of your dataset

data = dict(
    train=dict(
        type=dataset_type,
        data_prefix='data/datasets_nonveh_Type/train',
#         ann_file='data/datasets_nonveh_Type/meta/train.txt',
        classes=classes,
        pipeline=train_pipeline
    ),
    val=dict(
        type=dataset_type,
        data_prefix='data/datasets_nonveh_Type/val',
#         ann_file='data/datasets_nonveh_Type/meta/val.txt',
        classes=classes,
        pipeline=test_pipeline
    ),
    test=dict(
        type=dataset_type,
        data_prefix='data/datasets_nonveh_Type/test',
#         ann_file='data/datasets_nonveh_Type/meta/test.txt',
        classes=classes,
        pipeline=test_pipeline
    )
)

# Training schedule config
# lr is set for a batch size of 128
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
# learning policy
lr_config = dict(policy='step', step=[15])
runner = dict(type='EpochBasedRunner', max_epochs=200)
log_config = dict(interval=100)
```
我是按照 https://mmclassification.readthedocs.io/en/master/tutorials/new_dataset.html 里面的方式2来组织数据集的，也就是不需要ann_file，但是启动训练时得到如下报错：
```
2022-06-30 05:57:41,376 - mmcls - INFO - initialize LinearClsHead with init_cfg {'type': 'Normal', 'layer': 'Linear', 'std': 0.01}
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/workspace/mmclassification/mmcls/datasets/custom.py", line 170, in __init__
    test_mode=test_mode)
  File "/workspace/mmclassification/mmcls/datasets/base_dataset.py", line 51, in __init__
    self.data_infos = self.load_annotations()
  File "/workspace/mmclassification/mmcls/datasets/custom.py", line 214, in load_annotations
    self.ann_file, file_client_args=self.file_client_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/fileio/parse.py", line 44, in list_from_file
    with StringIO(file_client.get_text(filename, encoding)) as f:
  File "/opt/conda/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 1006, in get_text
    return self.client.get_text(filepath, encoding)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 535, in get_text
    with open(filepath, 'r', encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/imagenet/meta/val.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 203, in <module>
    main()
  File "tools/train.py", line 199, in main
    meta=meta)
  File "/workspace/mmclassification/mmcls/apis/train.py", line 200, in train_model
    val_dataset = build_dataset(cfg.data.val, dict(test_mode=True))
  File "/workspace/mmclassification/mmcls/datasets/builder.py", line 50, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: CustomDataset: [Errno 2] No such file or directory: 'data/imagenet/meta/val.txt'
```
因为我用了imagenet的base所以才会报这个错吗？那我应该用哪个base？Tutorial里也没有说明

**Comment by Ezra-Yu** [comment]
The program entered this [branch](https://github.com/open-mmlab/mmclassification/blob/d2e505415040bf5329ab218bb6fe3d899f176cd5/mmcls/datasets/custom.py#L212), means that your `ann_file` is a `str`. please use [`build_dataset`](https://github.com/open-mmlab/mmclassification/blob/d2e505415040bf5329ab218bb6fe3d899f176cd5/mmcls/datasets/__init__.py#L4) to debug.

**Comment by wolfryu** [comment]
I think you should delete this code:
`'../_base_/datasets/imagenet_bs32.py'`

**Comment by grapefruitL** [comment]
@wolfryu Thanks, it wroks
