### ISSUE TITLE
Error encountered when using customized dataset

### ISSUE THREAD

**Issue by liuquande** [open-mmlab/mmclassification#912]
Hi,

I am trying to use the customized dataset follwing the official instruction.

Specifically, my dataset contain two class "true" and "false", and I have organized the dataset dir as the second architecture (https://mmclassification.readthedocs.io/en/latest/tutorials/new_dataset.html) as follows:
![image](https://user-images.githubusercontent.com/29408526/179147249-5ce26d4c-7411-465b-b497-138d175f7a82.png)

and the config file of my customized dataset is as follows, which is **similar and cifar10_bs16.py but change the data_prefix and add "classes = ['true', 'false']"**:

![image](https://user-images.githubusercontent.com/29408526/179147534-4fcb7df6-83eb-4c01-92d5-b6c88d644f90.png)

When I am trying to train a model with this dataset, I got this error:

> 2022-07-15 12:01:29,057 - mmcls - INFO - workflow: [('train', 1)], max: 200 epochs
2022-07-15 12:01:29,057 - mmcls - INFO - Checkpoints will be saved to /apdcephfs/share_1041553/qdliu/cv_project/goal-prediction/mmclassification/work_dirs/mobilenet-v3-small_8xb16_custom by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 203, in <module>
    main()
  File "tools/train.py", line 191, in main
    train_model(
  File "/apdcephfs/share_1041553/qdliu/cv_project/goal-prediction/mmclassification/mmcls/apis/train.py", line 240, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 130, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/apdcephfs/share_1041553/qdliu/anaconda3/envs/open-mmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/apdcephfs/share_1041553/qdliu/cv_project/goal-prediction/mmclassification/mmcls/datasets/base_dataset.py", line 97, in __getitem__
    return self.prepare_data(idx)
  File "/apdcephfs/share_1041553/qdliu/cv_project/goal-prediction/mmclassification/mmcls/datasets/base_dataset.py", line 91, in prepare_data
    return self.pipeline(results)
  File "/apdcephfs/share_1041553/qdliu/cv_project/goal-prediction/mmclassification/mmcls/datasets/pipelines/compose.py", line 33, in __call__
    data = t(data)
  File "/apdcephfs/share_1041553/qdliu/cv_project/goal-prediction/mmclassification/mmcls/datasets/pipelines/transforms.py", line 101, in __call__
    img = results[key]
KeyError: 'img' 

Could you please give me some hint on how to solve it?
Many thanks.

Best.

**Comment by Ezra-Yu** [comment]
lack of 'LoadImgFromFile' transform, here is an [example](https://github.com/open-mmlab/mmclassification/blob/d2e505415040bf5329ab218bb6fe3d899f176cd5/configs/_base_/datasets/imagenet_bs256_rsb_a12.py#L8).

**Comment by liuquande** [comment]
Hi,

Many thanks for the reply. It works after adding "LoadImgFromFile".

Best.
