### ISSUE TITLE
MMCls Swin Transformer -Base output channels does not match with neck channels in MMDet     

### ISSUE THREAD

**Issue by foolhard** [open-mmlab/mmclassification#946]
Hello, 

I try to load **mmcls.SwinTransformer** base in **mmdet**, but failed  because the **output channels of Swin-B** **(256, 512, 1024, 1024)** don't match with **neck input channels** **(128, 256, 512, 1024)** in official Swin-B object detection setting.

**How can I get the same output channels from Swin-B backbone as neck input channels in mmdet?** 

**Swin-B output channels**: 

    (norm0): LayerNorm((256,), eps=1e-05, elementwise_affine=True)
    (norm1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
    (norm2): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    (norm3): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)]
 
**Neck input channels:**

```python
[  (neck): FPN(
    (lateral_convs): ModuleList(
      (0): ConvModule(
        (conv): Conv2d(128, 256, kernel_size=(1, 1), stride=(1, 1))
      )
      (1): ConvModule(
        (conv): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
      )
      (2): ConvModule(
        (conv): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1))
      )
      (3): ConvModule(
        (conv): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1))
      )
    )]
```

### Post related information

1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
   \[mmcls                   0.23.0
mmcv-full               1.4.2
torch                   1.9.0
torchaudio              0.9.0a0+33b2469
torchvision             0.10.0\]
2. Your config file if you modified it or created a new one.

```python
[_base_ = [
    '../_base_/models/mask_rcnn_r50_fpn.py',
    '../_base_/datasets/coco_instance.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]

pretrained = 'ckpts/swin-base_3rdparty_in21k.pth'

# please install mmcls>=0.22.0
# import mmcls.models to trigger register_module in mmcls
custom_imports = dict(imports=['mmcls.models'], allow_failed_imports=False)
checkpoint_file = 'https://download.openmmlab.com/mmclassification/v0/convnext/downstream/convnext-tiny_3rdparty_32xb128-noema_in1k_20220301-795e9634.pth'  # noqa

model = dict(
    backbone=dict(
        _delete_=True,
        type='mmcls.SwinTransformer',
        arch='base',
        img_size=224,
        drop_path_rate=0.2,
        out_indices=(0, 1, 2, 3),
#         init_cfg=dict(type='Pretrained', checkpoint=checkpoint_file,prefix='backbone.')
    ),
    neck=dict(in_channels=[128, 256, 512, 1024])
)

optimizer = dict(
    _delete_=True,
    type='AdamW',
    lr=0.0001,
    betas=(0.9, 0.999),
    weight_decay=0.05,
    paramwise_cfg=dict(
        custom_keys={
            'absolute_pos_embed': dict(decay_mult=0.),
            'relative_position_bias_table': dict(decay_mult=0.),
            'norm': dict(decay_mult=0.)
        }))
lr_config = dict(warmup_iters=1000, step=[8, 11])
runner = dict(max_epochs=12)]
```

3. Your train log file if you meet the problem during training.
   \[Traceback (most recent call last):
  File "tools/train.py", line 246, in <module>
    main()
  File "tools/train.py", line 242, in main
    meta=meta)
  File "/dfs/data/open_mmlab/mmdet_panoptic/mmdet/apis/train.py", line 244, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/dfs/data/miniconda/envs/panoptic/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/dfs/data/miniconda/envs/panoptic/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/dfs/data/miniconda/envs/panoptic/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/dfs/data/miniconda/envs/panoptic/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/dfs/data/open_mmlab/mmdet_panoptic/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/dfs/data/miniconda/envs/panoptic/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/dfs/data/miniconda/envs/panoptic/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/dfs/data/open_mmlab/mmdet_panoptic/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/dfs/data/open_mmlab/mmdet_panoptic/mmdet/models/detectors/two_stage.py", line 127, in forward_train
    x = self.extract_feat(img)
  File "/dfs/data/open_mmlab/mmdet_panoptic/mmdet/models/detectors/two_stage.py", line 69, in extract_feat
    x = self.neck(x)
  File "/dfs/data/miniconda/envs/panoptic/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/dfs/data/miniconda/envs/panoptic/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/dfs/data/open_mmlab/mmdet_panoptic/mmdet/models/necks/fpn.py", line 159, in forward
    for i, lateral_conv in enumerate(self.lateral_convs)
  File "/dfs/data/open_mmlab/mmdet_panoptic/mmdet/models/necks/fpn.py", line 159, in <listcomp>
    for i, lateral_conv in enumerate(self.lateral_convs)
  File "/dfs/data/miniconda/envs/panoptic/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/dfs/data/miniconda/envs/panoptic/lib/python3.7/site-packages/mmcv/cnn/bricks/conv_module.py", line 201, in forward
    x = self.conv(x)
  File "/dfs/data/miniconda/envs/panoptic/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/dfs/data/miniconda/envs/panoptic/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/dfs/data/miniconda/envs/panoptic/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 440, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [256, 128, 1, 1], expected input[2, 256, 100, 152] to have 128 channels, but got 256 channels instead\]

**Comment by mzr1996** [comment]
Got it, swin in mmdet output before the downsample layer. I will implement it and create a PR today, please wait.

**Comment by mzr1996** [comment]
I'm sorry that it's a design mistake.
Please use the code in https://github.com/open-mmlab/mmclassification/pull/947 and try again.

**Comment by foolhard** [comment]
I verified the code and it works well. 
Thanks for your quick action.
