### ISSUE TITLE
RecursionError using own dataset

### ISSUE THREAD

**Issue by ifarady** [open-mmlab/mmclassification#949]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

Well, this is my first issue, so apology for any mistake. Basically, i want to train a network with my own dataset. I followed the customized dataset with a special structure. I encounter RecursionError: maximum recursion depth exceeded that I have n idea how to solve this problem.

my dataset structure:
dataset/train/class-1/img.jpg, img2.jpg...
----------------/class-2/img.jpg, img2.jpg...
----------------/class-3/img.jpg, img2.jpg...

dataset/val/class-1/img.jpg, img2.jpg...
----------------/class-2/img.jpg, img2.jpg...
----------------/class-3/img.jpg, img2.jpg...

dataset/test/class-1/img.jpg, img2.jpg...
----------------/class-2/img.jpg, img2.jpg...
----------------/class-3/img.jpg, img2.jpg...

### Post related information

1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
mmcv-full          1.6.1
mmcls              0.23.2 
torch              1.12.0
torchvision        0.13.0
2. Your config file if you modified it or created a new one.

```python
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='ResNet',
        depth=18,
        num_stages=4,
        out_indices=(3, ),
        style='pytorch'),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=3,
        in_channels=512,
        loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
        topk=(1, 5)))
dataset_type = 'CustomDataset'
classes = None
img_norm_cfg = dict(
    mean=[125.307, 122.961, 113.8575],
    std=[51.5865, 50.847, 51.255],
    to_rgb=False)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomCrop', size=32, padding=4),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(
        type='Normalize',
        mean=[125.307, 122.961, 113.8575],
        std=[51.5865, 50.847, 51.255],
        to_rgb=False)
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='Normalize',
        mean=[125.307, 122.961, 113.8575],
        std=[51.5865, 50.847, 51.255],
        to_rgb=False),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=1,
    train=dict(
        type='CustomDataset',
        data_prefix='data/cor/train/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='RandomCrop', size=32, padding=4),
            dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
            dict(
                type='Normalize',
                mean=[125.307, 122.961, 113.8575],
                std=[51.5865, 50.847, 51.255],
                to_rgb=False)
        ]),
    val=dict(
        type='CustomDataset',
        data_prefix='data/cor/test',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='Normalize',
                mean=[125.307, 122.961, 113.8575],
                std=[51.5865, 50.847, 51.255],
                to_rgb=False),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ],
        test_mode=True),
    test=dict(
        type='CustomDataset',
        data_prefix='data/cor/test',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='Normalize',
                mean=[125.307, 122.961, 113.8575],
                std=[51.5865, 50.847, 51.255],
                to_rgb=False),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ],
        test_mode=True))
evaluation = dict(interval=1, metric='accuracy')
optimizer = dict(type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(policy='step', step=[100, 150])
runner = dict(type='EpochBasedRunner', max_epochs=20)
checkpoint_config = dict(interval=1)
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
work_dir = './work_dirs/resnet18_8xb16_cifar10-copy'
gpu_ids = [0]
```

3. Your train log file if you meet the problem during training.
   \[here\]
4. Other code you modified in the `mmcls` folder.
-------------------- 
2022-08-02 14:20:14,082 - mmcls - INFO - workflow: [('train', 1)], max: 20 epochs
2022-08-02 14:20:14,082 - mmcls - INFO - Checkpoints will be saved to /home/isack/mmclassification/work_dirs/resnet18_8xb16_cifar10-copy by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 205, in <module>
    main()
  File "tools/train.py", line 193, in main
    train_model(
  File "/home/isack/mmclassification/mmcls/apis/train.py", line 228, in train_model
    runner.run(data_loaders, cfg.workflow)
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 49, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
RecursionError: Caught RecursionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 79, in collate
    return {
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 80, in <dictcomp>
    key: collate([d[key] for d in batch], samples_per_gpu)
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 77, in collate
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 77, in <listcomp>
    return [collate(samples, samples_per_gpu) for samples in transposed]
*
*
*
 File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 77, in <listcomp>
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 77, in collate
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 77, in <listcomp>
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmcv/parallel/collate.py", line 23, in collate
    if not isinstance(batch, Sequence):
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/abc.py", line 98, in __instancecheck__
    return _abc_instancecheck(cls, instance)
  File "/home/isack/anaconda3/envs/openmmlab/lib/python3.8/abc.py", line 102, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
RecursionError: maximum recursion depth exceeded

**Comment by mzr1996** [comment]
A typical train pipeline setting:
```python
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomResizedCrop', size=224),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
```
Please add the last three lines and try again.

**Comment by ifarady** [comment]
Thanks for your speedy reply. It works! really appreciate that. Thank you.
