### ISSUE TITLE
KeyError: 'ImageClassifier: "LinearClsHead: \'L1Loss is not in the models registry\'"'

### ISSUE THREAD

**Issue by xiaoluobie** [open-mmlab/mmclassification#959]
### Checklist

- I have searched related issues but cannot get the expected help. yes
- I have read related documents and don't know what to do. yes

#### Encounter this error message:
```python
Traceback (most recent call last):
  File "/root/autodl-tmp/ABC/mmclassification-master/tools/train.py", line 194, in <module>
    main()
  File "/root/autodl-tmp/ABC/mmclassification-master/tools/train.py", line 164, in main
    model = build_classifier(cfg.model)
  File "/root/mmclassification/mmcls/models/builder.py", line 38, in build_classifier
    return CLASSIFIERS.build(cfg)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: 'ImageClassifier: "LinearClsHead: \'L1Loss is not in the models registry\'"'
```

### Post related information

1. The output of`pip list | grep "mmcv\|mmcls\|^torch"`
```python
mmcls                          0.23.2              /root/mmclassification
mmcv-full                      1.5.0
torch                          1.6.0+cu101
torchvision                    0.7.0+cu101

```
2. Your config file if you modified it or created a new one.

```python
model = dict(
    type='ImageClassifier',
    backbone=dict(
        type='ResNet',
        depth=18,
        num_stages=4,
        out_indices=(3, ),
        style='pytorch'),
    neck=dict(type='GlobalAveragePooling'),
    head=dict(
        type='LinearClsHead',
        num_classes=102,
        in_channels=512,
        loss=dict(type='L1Loss', loss_weight=1.0),#L1Loss CrossEntropyLoss
        topk=(1, 5)))
dataset_type = 'ImageNet'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='RandomResizedCrop', size=224),
    dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='ToTensor', keys=['gt_label']),
    dict(type='Collect', keys=['img', 'gt_label'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='Resize', size=(256, -1)),
    dict(type='CenterCrop', crop_size=224),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='ImageToTensor', keys=['img']),
    dict(type='Collect', keys=['img'])
]
data = dict(
    samples_per_gpu=32,
    workers_per_gpu=2,
    train=dict(
        type='ImageNet',
        # data_prefix='D:\\eclipse-workspace\\PyTorch4\\mmclassification-master\\mmcls\\data\\flower_data\\train_filelist',
        data_prefix='E:\\Computer Vision\\Tangyudi teacher\\examples\\MMLAB\\classfication\\mmclassification-master\\mmcls\\data\\flower_data\\train',
        # ann_file='D:\\eclipse-workspace\\PyTorch4\\mmclassification-master\\mmcls\\data\\flower_data\\train.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='RandomResizedCrop', size=224),
            dict(type='RandomFlip', flip_prob=0.5, direction='horizontal'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='ToTensor', keys=['gt_label']),
            dict(type='Collect', keys=['img', 'gt_label'])
        ]),
    val=dict(
        type='ImageNet',
        # data_prefix='../mmcls/data/flower_data/val_filelist',
        data_prefix='E:\\Computer Vision\\Tangyudi teacher\\examples\\MMLAB\\classfication\\mmclassification-master\\mmcls\\data\\flower_data\\valid',
        # ann_file='../mmcls/data/flower_data/val.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=(256, -1)),
            dict(type='CenterCrop', crop_size=224),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ]),
    test=dict(
        type='ImageNet',
        data_prefix='E:\\Computer Vision\\Tangyudi teacher\\examples\\MMLAB\\classfication\\mmclassification-master\\mmcls\\data\\flower_data\\valid',
        # ann_file='../mmcls/data/flower_data/val.txt',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='Resize', size=(256, -1)),
            dict(type='CenterCrop', crop_size=224),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ]))
evaluation = dict(interval=10, metric='accuracy')
optimizer = dict(type='SGD', lr=0.1, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(policy='step', step=[30, 60, 90])
runner = dict(type='EpochBasedRunner', max_epochs=100)
checkpoint_config = dict(interval=50)
log_config = dict(interval=100, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
work_dir = 'E:\\Computer Vision\\Tangyudi teacher\\bili\mmclassification-master\\tools\work_dirs\\resnet18_8xb32_in1k'

gpu_ids = [0]

```

3. Your train log file if you meet the problem during training.
   \[Training cannot start\]

**Comment by mzr1996** [comment]
Where is the implementation of `L1loss`?

**Comment by xiaoluobie** [comment]
```python
    head=dict(
        type='LinearClsHead',
        num_classes=102,
        in_channels=512,
        loss=dict(type='L1Loss', loss_weight=1.0),#L1Loss CrossEntropyLoss
        topk=(1, 5)))
```
Fully connected network

**Comment by mzr1996** [comment]
It's only a configuration file. We don't have an official implementation of `L1loss` and if you want to use it, you need to add it manually according to the tutorial https://mmclassification.readthedocs.io/en/master/tutorials/new_modules.html#add-new-loss

**Comment by xiaoluobie** [comment]
I see. Thank you

**Comment by xiaoluobie** [comment]
I see. Thank you
