### ISSUE TITLE
Server socket address error after installation!

### ISSUE THREAD

**Issue by shim94kr** [open-mmlab/mmclassification#960]
### Describe the question you meet

I follow the instruction for installation and run the command as follows.

./tools/dist_train.sh configs/resnet/resnet18_8xb16_cifar10.py 4

Currently I use my remote server, but I meet the following error, which is related to server socket.

Is there any way to analyse or solve it? Any comments or help would be appreciated!

*****************************************
[W socket.cpp:401] [c10d] The server socket has failed to bind to [::]:22 (errno: 98 - Address already in use).
[W socket.cpp:401] [c10d] The server socket has failed to bind to 0.0.0.0:22 (errno: 98 - Address already in use).
[E socket.cpp:435] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/run.py", line 755, in run
    )(*cmd_args)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 236, in launch_agent
    result = agent.run()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/elastic/agent/server/api.py", line 844, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/elastic/agent/server/api.py", line 678, in _initialize_workers
    self._rendezvous(worker_group)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/elastic/agent/server/api.py", line 538, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/elastic/rendezvous/static_tcp_rendezvous.py", line 61, in next_rendezvous
    multi_tenant=True,
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:22 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:22 (errno: 98 - Address already in use).

**Comment by mzr1996** [comment]
Please run `export MASTER_PORT=29500` and try again.

**Comment by shim94kr** [comment]
@mzr1996  Thank you for answering my question.

But sadly, the same error occurs with the command you suggested.

**Comment by mzr1996** [comment]
What's the error report?

**Comment by shim94kr** [comment]
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/4125005/184147808-ef96bd2a-f01d-4111-835a-0b05f58ac38b.png">

The same error appears..

**Comment by shim94kr** [comment]
<img width="294" alt="image" src="https://user-images.githubusercontent.com/4125005/184564988-4e9bfe45-a733-4b2d-8c1d-aada4cf6da55.png">

It raises the error as it uses the port 22 by default. Directly assigning a random 4-digits number addresses the issue for my server.

Thank you!

**Comment by mzr1996** [comment]
The default port should be `29500` instead of `22` here, did you modify it?

**Comment by shim94kr** [comment]
No, but the server gets 22 as the default port. I think it needs to be set directly by a number, not by the ${PORT: -29500}.
