### ISSUE TITLE
[Bug] "configs/_base_/models/mobilenet-v3-small_8xb16_cifar.py" does not exist

### ISSUE THREAD

**Issue by GreatV** [open-mmlab/mmclassification#979]
### Describe the bug

"mmclassification/configs/_base_/models/mobilenet-v3-small_8xb16_cifar.py" does not exist

\[here\]

### To Reproduce

The command you executed.

```shell
export MMCLS_DIR=mmclassification
export CONFIG_PATH=configs/mobilenet_v3/mobilenet_v3_small_cifar.py
export MODEL_DIR=work

cd ${MMCLS_DIR}

python tools/train.py ${CONFIG_PATH} --work-dir ${MODEL_DIR}
```

### Post related information

1. The output of `pip list | grep "mmcv\|mmcls\|^torch"`
```
mmcv-full               1.6.0
torch                   1.10.0
torchvision             0.11.1
```
3. Your config file if you modified it or created a new one.

```python
[here]
```

4. Your train log file if you meet the problem during training.
```
Traceback (most recent call last):
  File "tools/train.py", line 205, in <module>
    main()
  File "tools/train.py", line 93, in main
    cfg = Config.fromfile(args.config)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/config.py", line 341, in fromfile
    use_predefined_variables)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/config.py", line 252, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/config.py", line 252, in _file2dict
    _cfg_dict, _cfg_text = Config._file2dict(osp.join(cfg_dir, f))
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/config.py", line 183, in _file2dict
    check_file_exist(filename)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/path.py", line 23, in check_file_exist
    raise FileNotFoundError(msg_tmpl.format(filename))
FileNotFoundError: file "/home/user/mmclassification/configs/_base_/models/mobilenet-v3-small_8xb16_cifar.py" does not exist
```
5. Other code you modified in the `mmcls` folder.
   \[here\]

### Additional context

\[here\]

**Comment by Ezra-Yu** [comment]
please try to change the `../_base_/models/mobilenet_v3_small_8xb16_cifar.py` to `../_base_/models/mobilenet_v3_small_cifar.py` in file https://github.com/open-mmlab/mmclassification/blob/90254a845540650bd03bc2b6108251825935c687/configs/mobilenet_v3/mobilenet-v3-small_8xb16_cifar10.py#L2.
